### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:87

### ISSUE THREAD

**Issue by z744364418p** [wentaozhu/DeepLung#1]
这个什么原因？

**Comment by wentaozhu** [comment]
How about running "nvidia-smi" in your terminal? I think it is because you did not configured the pytorch right.

**Comment by jjqtony** [comment]
I got:
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/cuda/Module.cpp:81

and the result of nvidia-smi is:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.69                 Driver Version: 384.69                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
| 35%   39C    P8    12W / 160W |     99MiB /  8110MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1034    G   /usr/lib/xorg/Xorg                              97MiB |
+-----------------------------------------------------------------------------+

**Comment by wentaozhu** [comment]
I think it is the code's error. It is the error for your GPU configuration.
