### ISSUE TITLE
question about froc

### ISSUE THREAD

**Issue by yulin9511** [wentaozhu/DeepLung#102]
请问frocwrtdeptepchluna16.py里的detp是froc曲线的y轴吗，我看到注释里的range是(-1,0,1)，怎样可以得到类似您论文中的froc曲线呢？
期待您的回复

**Comment by wentaozhu** [comment]
You can directly run noduleCADEvaluationLUNA16.py, and get the performance in the paper.

**Comment by yulin9511** [comment]
thank you

**Comment by yulin9511** [comment]
请问detp取值一般取几个呢，如果只取-1会影响最终结果吗？
期待您的回复

**Comment by wentaozhu** [comment]
should be validated on validation set. You can select from [-3, -2.5, -2, -1.5, -1, 0, 0.5]
