### ISSUE TITLE
About 10-fold cross-validation

### ISSUE THREAD

**Issue by tan416tan** [wentaozhu/DeepLung#103]
Is the same pretraining file used when you perform a 10-fold cross-validation?For example, you give 064.ckpt.

**Comment by wentaozhu** [comment]
Yes. It is for residual model.

**Comment by tan416tan** [comment]
Thanks for your reply.
In run_training.sh，What does "config_training$f" mean? Could it be changed to "config_training"？
![image](https://user-images.githubusercontent.com/49237793/71614521-22d44d80-2be7-11ea-8df3-711ad3428b8c.png)

**Comment by wentaozhu** [comment]
It is for 10-fold cross validation.

**Comment by tan416tan** [comment]
> It is for 10-fold cross validation.

thank you,i see
