### ISSUE TITLE
where dose 'annotationdetclsgt.csv' comes

### ISSUE THREAD

**Issue by Ayanamiyui** [wentaozhu/DeepLung#104]
Sorry i have a question about 'annotationdetclsgt.csv' in dataconvert.py. Where dose it come from? I'm confused that is it given in IDLC DATASET? Its the ground truth with malignant. But I didn't find it in LUNA16 dataset .Thanks for answering, best wishes.

**Comment by wentaozhu** [comment]
Thank you so much for your interest!

Is it https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/annotationdetclsconvfnl_v3.csv ?

**Comment by wentaozhu** [comment]
Or you can use https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/extclsshpinfo.py to generate it.

**Comment by Ayanamiyui** [comment]
> Thank you so much for your interest!
> Is it https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/annotationdetclsconvfnl_v3.csv ?

Thanks for replying! But what I really mean is the csv file called in https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/dataconvert.py in 28th line, which is 'pdframe = pd.read_csv('annotationdetclsgt.csv', names=['seriesuid', 'coordX', 'coordY', 'coordZ', 'diameter_mm', 'malignant'])'. I have a question about how this file came. Thank you for your responding!

**Comment by Ayanamiyui** [comment]
> Or you can use https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/extclsshpinfo.py to generate it.

@wentaozhu thanks for replying! Is 'annotationdetclsgt.csv' same as 'annotationdetclssgm.csv' which is generated in extclsshpinfo.py?

**Comment by wentaozhu** [comment]
I think so. You can have a check.
