### ISSUE TITLE
跑测试集时的一些问题

### ISSUE THREAD

**Issue by Alexander0211** [wentaozhu/DeepLung#106]
1. nodcls/是用来对检测到的肿瘤进行二分类的对吗？
2. 我在运行evaluationScript/frocwrtdetpepchluna16.p时发现计算nms、iou时速度太慢了，导致内溢出，请问如何解决？您有遇到过类似情况吗？

**Comment by wentaozhu** [comment]
1 Yes
2 Yes. NMS is slow. It only uses CPU memory. It can be easily solved by adding more GPU memory or you can try to clean some temporary variables.
