### ISSUE TITLE
Are there some guides to run the code succesfully?

### ISSUE THREAD

**Issue by 3learning12340** [wentaozhu/DeepLung#107]
Are there some guides to run the code succesfully? this code is huge and  I can not find any details to run this code. I am confused about running this code after I download this code.

**Comment by wentaozhu** [comment]
Did you find out how to run? Download the data from the instructions of readme and run the "python AnatomyNet.py".

**Comment by 3learning12340** [comment]
Thank you very much. I will try as you say.
