### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by 3learning12340** [wentaozhu/DeepLung#110]
When I run the code /detector/main.py, the error "AttributeError: module 'object' has no attribute 'rebuild tensor'" occurs. I check this error on the website and it shows the reason is that pytorch version is too low. However, I install torch==0.1.10(torch-0.1.10.post2-cp27-none-linux_x86_64.whl) as the page said. I guess whether I misunderstand the meaning of pytorch (0.1.10+ac9245a) ?

**Comment by wentaozhu** [comment]
How about install pytorch 0.1.9?

**Comment by 3learning12340** [comment]
I install torch==1.1.0 and it works. But when I train the code detector/main.py, it shows error  CUDA out of meomery. I find the reason is that test(test_loader, net, get_pbb, save_dir,config)  needs too much CUDA meomery. Before run this code --test(test_loader, net, get_pbb, save_dir,config), My computer's CUDA meomery is enough. Athough I decrease the batch_size to 8 and num_workers to  10, this code "test(test_loader, net, get_pbb, save_dir,config)" also needs too much CUDA meomery. I am thinking how to solve the problem.

**Comment by 3learning12340** [comment]
After I read the source code and some relevant materials, I find the problem is that the input image size is 96x96x96 in the train process, but the size is 208x208x208 in the test process. the image size(208x208x208) is too big for my computer, so I decrease the margin and sidelen to a proper value and it works. Finally, thank you for your patient reply.
