### ISSUE TITLE
train dpn model

### ISSUE THREAD

**Issue by 3learning12340** [wentaozhu/DeepLung#113]
As for res18, we can train res18 based on 064.ckpt. However, I want to train dpn3d26, I don't know resume which pretrained model.  Before raising the issues, I find the same question at #94, but I don't unsterstand the reply as #94 said. I think the models of the path ---  detector/dpnmodel have been  trained well by author and those models don't need to be trained any more. Just like the models in the path --- detector/res18model. I have tested the model fd9044.ckpt based on subset9 and obtained the froc which is about 0.8. Therefore, I think pretrained model should not be the model in the path---detector/dpnmodel, because those have benn trained well. Did I get it right?

**Comment by 3learning12340** [comment]
Besides, how to generate the pretrained model 064.ckpt which is used in res18 ? I don't know how the 064.ckpt is generated. I am looking forward to your reply and sorry to bother you again.

**Comment by wentaozhu** [comment]
> As for res18, we can train res18 based on 064.ckpt. However, I want to train dpn3d26, I don't know resume which pretrained model. Before raising the issues, I find the same question at #94, but I don't unsterstand the reply as #94 said. I think the models of the path --- detector/dpnmodel have been trained well by author and those models don't need to be trained any more. Just like the models in the path --- detector/res18model. I have tested the model fd9044.ckpt based on subset9 and obtained the froc which is about 0.8. Therefore, I think pretrained model should not be the model in the path---detector/dpnmodel, because those have benn trained well. Did I get it right?

Yes. They are trained well. Please also check resmodel

**Comment by wentaozhu** [comment]
Please check #109 for 064.ckpt.

**Comment by 3learning12340** [comment]
Thank you for your reply.
