### ISSUE TITLE
where is besttestpred.npy?

### ISSUE THREAD

**Issue by 3learning12340** [wentaozhu/DeepLung#114]
Thank you for sharing the program at first, but I met some problems. When I run the code "humanperformance.py", the system remind me "No such file or directory: '../../../CTnoddetector/training/nodcls/besttestpred.npy'". I don't find the file in my directory and I want to know how to generate it?before I run the code  "humanperformance.py", I have already run  ./data/extclsshpinfo.py to extract nodule labels. Besides, I find the same question in 90#, but I don't find any code to generate besttestpred.npy In the training of classifier. Looking forward to your reply.

**Comment by 3learning12340** [comment]
In the paper, I find there is a process in nocule classification that we need to crop the nodule with the size of 32x32x32, where is this part of code?

**Comment by 3learning12340** [comment]
In the training process of nodule detection, I find the network need more GPU memory when I use DPN model, compared to res18 model. Because the number of network parameters is proportional to GPU memory, I think DPN model needs more parameters than res18. However, in the paper, you said DPN model needed 1/4 parameters of res18, I am confused about the parameters.

**Comment by wentaozhu** [comment]
> In the training process of nodule detection, I find the network need more GPU memory when I use DPN model, compared to res18 model. Because the number of network parameters is proportional to GPU memory, I think DPN model needs more parameters than res18. However, in the paper, you said DPN model needed 1/4 parameters of res18, I am confused about the parameters.

Yes. However the dense connection in DPN consumes more memory probably because of more feature maps.

**Comment by wentaozhu** [comment]
> Thank you for sharing the program at first, but I met some problems. When I run the code "humanperformance.py", the system remind me "No such file or directory: '../../../CTnoddetector/training/nodcls/besttestpred.npy'". I don't find the file in my directory and I want to know how to generate it?before I run the code "humanperformance.py", I have already run ./data/extclsshpinfo.py to extract nodule labels. Besides, I find the same question in 90#, but I don't find any code to generate besttestpred.npy In the training of classifier. Looking forward to your reply.

You can train the classifier based on the code https://github.com/wentaozhu/DeepLung/blob/master/nodcls/main_nodcls.py
And write a script to get the prediction.
