### ISSUE TITLE
Where is the annotationdetclsconvfnl_v3.csv

### ISSUE THREAD

**Issue by elaboraty777** [wentaozhu/DeepLung#115]
when I study the nodcls codes,I found the annotationdetclsconvfnl_v3.csv and /crop_v3/  folder are No explanation.Could you tell me how to get these,thanks.

**Comment by wentaozhu** [comment]
The annotationdetclsconv_v3.csv is from https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/dataconverter.py
