### ISSUE TITLE
some questions about pthumanperformance.py

### ISSUE THREAD

**Issue by 3learning12340** [wentaozhu/DeepLung#116]
When I was running  the code pthumanperformance.py, ZeroDivisionError: float division by zero occured. I debug each line of the code and find the problem.I find the results that  n[0]=43, n[1]=12, n[2]=3, n[3]=0, np[0]=2, np[1]=10, np[2]=3, np[3]=0, so (n[2]-np[2]) is equal to zero. There should be four results, but I can only get two results. This is shown as follows.
![pthumanperformance](https://user-images.githubusercontent.com/48426776/85943610-b94db580-b963-11ea-83fa-ec92bab1e415.png)
I find the root of the problem that there are not enough nodule tags in extantvlu[1]. There are most three nodule tags in extantvlu[1] which are obtained from list3.2.xls. This is shown as follows. I am looking forward to your reply and thank you very much.
![pthumanperformance2](https://user-images.githubusercontent.com/48426776/85943852-51986a00-b965-11ea-86fe-f49abe7015fc.png)

**Comment by wentaozhu** [comment]
Yes. The data processing is pretty time-consuming. At the time of writing code, I had indeed taken a lot of time to analyze the data. Thank you so much for the interest!
