### ISSUE TITLE
How to change *_lbb.npy to the .mha file?

### ISSUE THREAD

**Issue by yl255** [wentaozhu/DeepLung#118]
Hi,
When I run the main.py with "--test 1",
I got the the result folder "./bbox" which contain some *_pbb.npy and *_lbb.npy files.
I want to change them to the .mha file.
But I do not know how to do.
Hope you can help me :)
Best,
Yaliang

**Comment by wentaozhu** [comment]
You can write python script to transform numpy format to your format.

**Comment by yl255** [comment]
Hi,
Thanks a lot for your reply.
Do you have some examples of the script to show how to do that?
Best,
Yaliang
