### ISSUE TITLE
What should I do if I use Your Excellent Work in CPU mode?

### ISSUE THREAD

**Issue by TracelessLe** [wentaozhu/DeepLung#12]
Recently, I'm trying to use part of your excellent work in nodule dectection. Be more exact, I use the detection net of Deeplung to **test** on my CT data. But I need to transform the GPU mode into CPU, what should I modify in the test part of "main.py" in the "detector" folder? 
I hope to receive your reply. Thanks.

**Comment by wentaozhu** [comment]
You can take a look at how to use CPU in pytorch. We use pytorch for the implementation. Thank you very much for your interest!

**Comment by TracelessLe** [comment]
Thanks a lot.
