### ISSUE TITLE
About using *_extendbox.npy data

### ISSUE THREAD

**Issue by yl255** [wentaozhu/DeepLung#120]
Hi,
The *_extendbox.npy data was created by the Mask data(or segment data) in the **prepare.py**.
And in the function **convertcsv** which is in the evaluationScript/**frocwrtdetpepchluna16.py** file,
it use the _extendbox.npy data to get the return result **rowlist**.
The code:
 `extendbox = np.load(os.path.join(sideinfopath, bboxfname[:-8]+'_extendbox.npy'), mmap_mode='r')`
...
`pbb[:, 1:] = np.array(pbb[:, 1:] + np.expand_dims(extendbox[:,0], 1).T)`
...

If there is a new data without segment, how to get the *_extendbox.npy data?
Best,
Yaliang

**Comment by wentaozhu** [comment]
If you use savenpy() in https://github.com/wentaozhu/DeepLung/blob/master/prepare.py#L292, you do not need the segmentation.

If you have, you can use https://github.com/wentaozhu/DeepLung/blob/master/prepare.py#L491

**Comment by yl255** [comment]
> If you use savenpy() in https://github.com/wentaozhu/DeepLung/blob/master/prepare.py#L292, you do not need the segmentation.
> 
> If you have, you can use https://github.com/wentaozhu/DeepLung/blob/master/prepare.py#L491


Thanks for reply.
In the code to get the **extendbox** is:
`   

    newshape = np.round(np.array(Mask.shape)*spacing/resolution).astype('int')
    m1 = Mask==3
    m2 = Mask==4
    Mask = m1+m2   
 
    xx,yy,zz= np.where(Mask)
    box = np.array([[np.min(xx),np.max(xx)],[np.min(yy),np.max(yy)],[np.min(zz),np.max(zz)]])
    box = box*np.expand_dims(spacing,1)/np.expand_dims(resolution,1)
    box = np.floor(box).astype('int')
    margin = 5
    extendbox = np.vstack([np.max([[0,0,0],box[:,0]-margin],0),np.min([newshape,box[:,1]+2*margin],axis=0).T]).T
`
The **Mask** data come from the label data in the _seg-lungs-LUNA16_ floder.
If I have a new data which is not in the Luna dataset, how to get the **Mask** data?
I was just confused.
Best,
Yaliang

**Comment by wentaozhu** [comment]
Use https://github.com/wentaozhu/DeepLung/blob/master/prepare.py#L292
