### ISSUE TITLE
predict one mhd file?

### ISSUE THREAD

**Issue by ZhouXiaolong0** [wentaozhu/DeepLung#121]
how can I use the model to predict one mhd file to get the result?

**Comment by wentaozhu** [comment]
The same pipeline: 1 preprocessing in https://github.com/wentaozhu/DeepLung/blob/master/prepare.py#L292, 2 use the deep network to do the inference, 3 do postprocessing, nms, in https://github.com/wentaozhu/DeepLung/blob/master/DeepLungDetectionDemo/detector.ipynb
