### ISSUE TITLE
how can I use singletest function?

### ISSUE THREAD

**Issue by ZhouXiaolong0** [wentaozhu/DeepLung#122]
I find a function in main.py. I think the parmeter net is the model net, and the config is the config file, and splitfun is SplitComb.split and combinefun is SplitCombi.combine. But I dont know what the data should be, and I am not quite sure what I understood is right? 
Does anyone know what the data should be?

**Comment by wentaozhu** [comment]
Please check LUNA16 data structure and the preprocessing is in https://github.com/wentaozhu/DeepLung/blob/master/prepare.py

**Comment by ZhouXiaolong0** [comment]
> Please check LUNA16 data structure and the preprocessing is in https://github.com/wentaozhu/DeepLung/blob/master/prepare.py

thanks for reply, however that is not my problem. the prepare.py file will get "_clean.npy" and "_label.npy". when I use test function, it is taken these two file as input, but I assume that I dont have "_label.npy". what I have is "_clean.npy". and I want to try the inference, I think the singletest function may be is the solution. But I dont  know how to use the function.

**Comment by wentaozhu** [comment]
How about to create a dummy annotation so that you can have "_label.npy"? And check the predicted bounding box.

**Comment by wentaozhu** [comment]
Please check https://github.com/wentaozhu/DeepLung/issues/123 for test.

**Comment by ZhouXiaolong0** [comment]
thanks for your reply, I understood that way of test. I will try to writer a new dataloader to see whether I can figure this out. if I can not, then I will try the dummy annotation way. thank you for you kindly reply.
