### ISSUE TITLE
some questions about label

### ISSUE THREAD

**Issue by 3learning12340** [wentaozhu/DeepLung#125]
Firstly, thanks for sharing the code. I have run this code successfully for a while, and I got the same result as paper's result. However, I still have some questions. Firstly, I don't know how to generate "annotationdetclsconvfnl_v3.csv" and I view all issues for several times. Some issues got the same problem, but there are not clear or efficient solutions. Besides, I compare the file "annotationdetclssgm.csv" , "annotationdetclssgmfnl.csv" with "annotationdetclsconvfnl_v3.csv", I find a conflict between the three documents. The first two files("annotationdetclssgm.csv" , "annotationdetclssgmfnl.csv") are consistent and I know how to generate them. But the last file(annotationdetclsconvfnl_v3.csv) is not consistent with the first two files and I don't know how to generate it.  Most importantly, annotationdetclsconvfnl_v3.csv is used in  main_nodcls.py to classification, and annotationdetclsconvfnl_v3.csv is vital. is there any one know how to generate annotationdetclsconvfnl_v3.csv? why are there some conflicts between the three files("annotationdetclssgm.csv" , "annotationdetclssgmfnl.csv" with "annotationdetclsconvfnl_v3.csv")? I am confused  and looking forward to the explanation. Thanks very much.

**Comment by 3learning12340** [comment]
There is a supplement. I have checked the data/extclsshpinfo.py, dataconverter.py and so on, especially extclsshpinfo.py. I have generated annotationdetclsconvfnl.csv by extclsshpinfo.py. Is there a connection between annotationdetclsconvfnl.csv and annotationdetclsconvfnl_v3.csv ? Besides, for the answers of #104 issues,I have checked the code and  I think 'annotationdetclsgt.csv' should not be same as 'annotationdetclssgm.csv'. They should be two different documents.

**Comment by wentaozhu** [comment]
Yes. You are right. Thank you so much for the information. The project is a little old. I cannot remember the details clearly. Probably you can try to use these files to run classification and see whether you can reproduce the classification score. Thanks!
