### ISSUE TITLE
prediction of CT scan

### ISSUE THREAD

**Issue by luantunez** [wentaozhu/DeepLung#127]
Can I predict the metrics given by the model (size, coords, malignancy) by only using as input the .mhd study? I would like to use the pretrained model provided for this (as I understood this would be the 064.ckpt file) just for prediction of a given study. If possible, what is the procedure? 
Thank you

**Comment by wentaozhu** [comment]
Please check https://github.com/wentaozhu/DeepLung/blob/master/run_training.sh

You can first run `python prepare.py` to convert your data to numpy, and do the prediction / inference.

After that, you can visualize the detection result like this https://github.com/wentaozhu/DeepLung/blob/master/DeepLungDetectionDemo/detector.ipynb

**Comment by luantunez** [comment]
I am so sorry, I had not seen this second email when sending you the response to the first one. I will try the pipeline you explain here and come back to you
Thank you,
Lucía Antúnez
