### ISSUE TITLE
lunanod() in nodule classification

### ISSUE THREAD

**Issue by luantunez** [wentaozhu/DeepLung#129]
in line 132 of main_nodcls.py the function lunanod receives the following parameters:
testset = lunanod(tefnamelst, telabellst, tefeatlst, train=False, download=True, transform=transform_test)
put in dataloader.py it says they should be:
def __init__(self, npypath, fnamelst, labellst, featlst, train=True,
                 transform=None, target_transform=None,
                 download=False)
so npypath is not refereced. Should it be? what goes there?
Also, would you provide the trained model for dpn3d.py for nodule classification? do you have other already loaded checkpoints for noudule classification? If there are, where are them? In case of being the ones in the dpnmodel or resmodel folder, why are there so many? which one should I use for classification o any CT scan? (not necessarily from the luna data set)
Thank you very much!

**Comment by wentaozhu** [comment]
Yes. You should do detection first, then classification. The classification is based on detection, detected box. Try to run detection and get a sense of how to process the lung CT images.
