### ISSUE TITLE
Out of memory for training with GPU

### ISSUE THREAD

**Issue by TinaLiuCV** [wentaozhu/DeepLung#13]
Hi,

In process of repeating the training, I use 4 TITAN X GPUs with the original parameters from the code. The error message shows: "RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCStorage.cu:58 "
How many GPUs are you using for the training? Do you have the estimating memory size it will occupy? 

Thanks,
Jingya

**Comment by wentaozhu** [comment]
Dear Jingya,

I have tested both 4 and 8 GPUS. Maybe you can use a smaller batch size.

Wentao

**Comment by SuperInno** [comment]
maybe you can reduce the number of workers 

here is code in ./detector/main.py

parser.add_argument('-j', '--workers', default=30, type=int, metavar='N',
                    help='number of data loading workers (default: 32)')

change the 'default'  smaller

**Comment by TinaLiuCV** [comment]
I change the batch size to 1 and the problem is still there. Which GPU are you using and what is the size of each GPU? Many thanks.

**Comment by wentaozhu** [comment]
I used 4 1080 Ti. The GPU memory is 11 GB. You can monitor the GPU memory by 'nvidia-smi'. Can you tell me the exact issue? Also, try to update pytorch and cudnn.

**Comment by wentaozhu** [comment]
Maybe you can get the size of each block’s output information in the res18.py for debug purpose.

I found the exact issue in the google https://github.com/torch/cutorch/issues/559

I did not meet the issue. Maybe you should update cuda version and cudnn, and try to install latest pytorch by anaconda
