### ISSUE TITLE
model and faster rcnn 

### ISSUE THREAD

**Issue by ZhouXiaolong0** [wentaozhu/DeepLung#131]
In the paper, it is said that this model is based on the faster rcnn, but I don't understand where does this model borrow from faster rcnn or part of faster rcnn, considering the model did not use RPN or ROI pooling, I dont understand What have you borrowed from faster rcnn?

**Comment by wentaozhu** [comment]
We did use RPN and ROI pooling. Please read the paper and code carefully. https://arxiv.org/pdf/1801.09555.pdf Thank you!
