### ISSUE TITLE
HOW TO USE THESE CODES

### ISSUE THREAD

**Issue by MHansy** [wentaozhu/DeepLung#134]
#!/bin/bash
set -e

# python prepare.py
cd detector
maxeps=150
f=9
CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 64 --resume 064.ckpt --save-dir res18/retrft96$f/ --epochs $maxeps --config config_training$f
for (( i=1; i<=$maxeps; i+=1)) 
do
    echo "process $i epoch"
	
	if [ $i -lt 10 ]; then
	    CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 32 --resume results/res18/retrft96$f/00$i.ckpt --test 1 --save-dir res18/retrft96$f/ --config config_training$f
	elif [ $i -lt 100 ]; then 
	    CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 32 --resume results/res18/retrft96$f/0$i.ckpt --test 1 --save-dir res18/retrft96$f/ --config config_training$f
	elif [ $i -lt 1000 ]; then
	    CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 32 --resume results/res18/retrft96$f/$i.ckpt --test 1 --save-dir res18/retrft96$f/ --config config_training$f
	else
	    echo "Unhandled case"
    fi

    if [ ! -d "results/res18/retrft96$f/val$i/" ]; then
        mkdir results/res18/retrft96$f/val$i/
    fi
    mv results/res18/retrft96$f/bbox/*.npy results/res18/retrft96$f/val$i/
done

**Comment by MHansy** [comment]
I tried to make followup on the code on how to use them on the training process from the repository but i dont understand at all
.......Why there is the CUDA information etc

**Comment by wentaozhu** [comment]
You can set any CUDA in your own computer according to your GPU/machine configuration.

**Comment by MHansy** [comment]
> 
> 
> You can set any CUDA in your own computer according to your GPU/machine configuration.

Thanks for your guidance.
Kindly help me to understand at this point below. (here do you mean to put all npy files into one folder instead of separate files (subset0, subset1, subset2, ...., subset9) as generated by the "prepare.py"?

 'train_preprocess_result_path':'$LUNA16PROPOCESSPATH/', # contains numpy for the data and label, which is generated by              prepare.py
          'val_preprocess_result_path':'$LUNA16PROPOCESSPATH/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'$LUNA16PROPOCESSPATH/',

**Comment by wentaozhu** [comment]
I think you are right. You can have a try and if there is no any issue, the code can run and gets a result.
