### ISSUE TITLE
How to interpret the detector results

### ISSUE THREAD

**Issue by oliva-cool** [wentaozhu/DeepLung#135]
Hi ,
These days, I am reading your codes. But I struggle to understand  some parts, could you please explain a bit:
1. How to interpret the .pbb results? Why is its shape is two dims,for an example (2519424, 5) ? How to count the finnal predict the anchor acoording to the .pbb results? 
2. in the test phrase , why is the shape of data in one batch is 5 dims? What does the first dim mean?
Many thanks!

**Comment by wentaozhu** [comment]
1 Please check https://github.com/wentaozhu/DeepLung/tree/master/DeepLungDetectionDemo
2 Please check https://github.com/wentaozhu/DeepLung/tree/master/evaluationScript (position_x, position_y, position_z, radius, probability)

**Comment by oliva-cool** [comment]
oh, I see. Thanks!!!
