### ISSUE TITLE
Confused about Faster R-CNN

### ISSUE THREAD

**Issue by Vast-Stars** [wentaozhu/DeepLung#14]
This issue is also posted in https://github.com/uci-cbcl/DeepLung/issues/1

>  I have read the code and paper. The paper mentioned that Faster R-CNN is used in detection part. But I didn't see Faster R-CNN in the folder ./detector . I search for RPN or ROI Pooling but get nothing.
> 
> Did you complete Faster-RCNN function in the data preprocessing part?
> Or is it just using RCNN? (If my understanding of the code is correct, the original image was partitioned and data-enhanced during preprocessing, and then used as input to the model. Looks like RCNN)

**Comment by wentaozhu** [comment]
We did not use selective search for proposal candidates. Our framework is a little different from Faster R-CNN. The detection in DeepLung is one-stage. We did not use the bounding box refinement in the second stage of Faster R-CNN. This one-stage detection is a trend for both natural image object detection, and medical image object detection.

**Comment by Vast-Stars** [comment]
Oh, I see. Thx......(￣▽￣)"
