### ISSUE TITLE
AttributeError: 'str' object has no attribute 'shape'

### ISSUE THREAD

**Issue by MHansy** [wentaozhu/DeepLung#140]
Kindly help please to solve this Error.

180.27077340951683 46.90248396437199
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 30 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "main_nodcls.py", line 133, in <module>
    testset = lunanod(npypath, tefnamelst, telabellst, tefeatlst, train=False, download=True, transform=transform_test)
  File "/content/gdrive/MyDrive/UNET-CBAM/UNetClass/dataloader.py", line 59, in __init__
    if fentry.shape[0] != 17 or fentry.shape[1] != 17 or fentry.shape[2] != 17:
AttributeError: 'str' object has no attribute 'shape'

**Comment by MHansy** [comment]
> 
> 
> Kindly help please to solve this Error.
> 
> 180.27077340951683 46.90248396437199
> /usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 30 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
> cpuset_checked))
> Traceback (most recent call last):
> File "main_nodcls.py", line 133, in
> testset = lunanod(npypath, tefnamelst, telabellst, tefeatlst, train=False, download=True, transform=transform_test)
> File "/content/gdrive/MyDrive/UNET-CBAM/UNetClass/dataloader.py", line 59, in **init**
> if fentry.shape[0] != 17 or fentry.shape[1] != 17 or fentry.shape[2] != 17:
> AttributeError: 'str' object has no attribute 'shape'

This error is commnng from the dataloader.py during running the code main_nodcls.py

 self.test_data = []
            self.test_labels = []
            self.test_feat = featlst
            for label, fentry in zip(labellst, fnamelst):
                if fentry.shape[0] != 17 or fentry.shape[1] != 17 or fentry.shape[2] != 17:
                    print(fentry.shape, type(fentry), type(fentry)!='str')
                if type(fentry) != 'str':
                    self.test_data.append(fentry)
                    self.test_labels.append(label)
                    # print('1')
                else:
                    file = os.path.join(npypath, fentry)
                    self.test_data.append(np.load(file))
                    self.test_labels.append(label)
            self.test_data = np.concatenate(self.test_data)

**Comment by wentaozhu** [comment]
Yes. You might change the number of works to 4, as suggested. Change the number of workers does not affect the accuracy, but slow down the training speed.
