### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by ZhouXiaolong0** [wentaozhu/DeepLung#142]
Hello,

During the image preprocessing, you mentioned that First, we clip the raw data into [−1200, 600]. I wonder, what has changed into this range  [−1200, 600], and I dont quite understand why do you do that?

I would be very grateful if I could receive your reply.

**Comment by wentaozhu** [comment]
I think the step should be 1 clip 2 normalization. You may check the code for the detail. Thank you!
