### ISSUE TITLE
Reducing training image size

### ISSUE THREAD

**Issue by MHansy** [wentaozhu/DeepLung#145]
Hello wentaozhu

I want to reduce the training image size from 92x92x92 let say by setting at config['crop_size'] = [64, 64, 64].
my question is, is there any changes should I make with other parameters like:-

config['sizelim'] = 2.5 #3 #6. #mm
config['sizelim2'] = 10 #30
config['sizelim3'] = 20 #40
config['r_rand_crop'] = 0.3
config['pad_value'] = 170
radiusLim = [8.,120.]
scaleLim = [0.75,1.25]

How do they affect the crop_size?

**Comment by wentaozhu** [comment]
I remember you can also get a decent accuracy using 64x64x64.

**Comment by Itsanewday** [comment]
@wentaozhu Thanks for sharing the project. How can i reproduce the performance? Besides, i think in the paper, the residual block is normal, can i replace it with the pre-activation residuals?

**Comment by wentaozhu** [comment]
Yes. Definitely, you can change to any kind of network, like the 3D dual path network in the paper. You might check the issues reported in the repository and find out how to train and solve possible issues. Thank you so much for your interest!
