### ISSUE TITLE
How to train a dpn detector

### ISSUE THREAD

**Issue by Itsanewday** [wentaozhu/DeepLung#147]
Thanks for sharing the project. I want to know how to train a dpn detector, should I initialize the dpn with random or resume from some checkpoint like 064.ckpt(res18). By the way, when i train res18 with smaller batchsize like 8 or 16, the performance is poor. Can you help me? Thanks
![froc_predanno-2](https://user-images.githubusercontent.com/21170245/142368214-b9a6a9aa-7d47-48dc-80a4-7574d87f0161.png)

![froc_predanno-2](https://user-images.githubusercontent.com/21170245/142368167-d24213c2-5919-4ecb-b303-449765e64894.png)

**Comment by mqingkui** [comment]
when i train res18, and get model weights  from epoch 71， also get the same FROC results with you, have you ever encounter my problem? also, does  resume from 064.ckpt is wanted when training res18? thank you in advance.

**Comment by Itsanewday** [comment]
Hi，the 064.ckpt is a pretrained model on another dataset(maybe tianchi). So, we can finetuning the weights using luna16. 
Unfortunately, I failed to  reproduce the results. 
Good Luck!

**Comment by mqingkui** [comment]
Okey, thanks a lot for your reply

**Comment by wentaozhu** [comment]
> Thanks for sharing the project. I want to know how to train a dpn detector, should I initialize the dpn with random or resume from some checkpoint like 064.ckpt(res18). By the way, when i train res18 with smaller batchsize like 8 or 16, the performance is poor. Can you help me? Thanks ![froc_predanno-2](https://user-images.githubusercontent.com/21170245/142368214-b9a6a9aa-7d47-48dc-80a4-7574d87f0161.png)
> 
> ![froc_predanno-2](https://user-images.githubusercontent.com/21170245/142368167-d24213c2-5919-4ecb-b303-449765e64894.png)

Does increasing the batch size help? Also, try to use pre-trained weights. How did you get the second figure? It seems the second figure is good. Thank you so much for your interest!

**Comment by mqingkui** [comment]
> > Thanks for sharing the project. I want to know how to train a dpn detector, should I initialize the dpn with random or resume from some checkpoint like 064.ckpt(res18). By the way, when i train res18 with smaller batchsize like 8 or 16, the performance is poor. Can you help me? Thanks ![froc_predanno-2](https://user-images.githubusercontent.com/21170245/142368214-b9a6a9aa-7d47-48dc-80a4-7574d87f0161.png)
> > ![froc_predanno-2](https://user-images.githubusercontent.com/21170245/142368167-d24213c2-5919-4ecb-b303-449765e64894.png)
> 
> Does increasing the batch size help? Also, try to use pre-trained weights. How did you get the second figure? It seems the second figure is good. Thank you so much for your interest!

OK，thank you for your suggestion, I will have a try.
