### ISSUE TITLE
Why ConCatenate the cropped nodule pixel in the  nodule classification?

### ISSUE THREAD

**Issue by Itsanewday** [wentaozhu/DeepLung#148]
Hello, In the paper, you said that "We construct feature by concatenating the learned deep 3D DPN features (the second from the last layer (2,560 dimension)), nodule size, and raw 3D cropped nodule pixels. Thus, we got a 32768+1+2560 featue for classifition (GradientBoostingClassifier). It seems that the learned features(2560-d) useless.

**Comment by wentaozhu** [comment]
What did you mean? For GBM, more features typically offer better accuracy.

**Comment by Itsanewday** [comment]
I think there are too many features for the classification and may cause the overfitting. By the way, combining the learned feature and raw image is a great idea, but how to decide the weights? Thanks!

**Comment by wentaozhu** [comment]
It can be learned by the gradient boosting machine. Please check the DeepLung paper, WACV 2018 for more details. Thanks!
