### ISSUE TITLE
Train tianchi datastes

### ISSUE THREAD

**Issue by blakeliu** [wentaozhu/DeepLung#15]
When I use tianchi  data set to train detector model;, it often appears "RuntimeError: inconsistent tensor sizes" or "LabelMapping  print input_size[2] dimmesion not ok  "

Hope to get your help.

**Comment by wentaozhu** [comment]
How many samples for this error? If it is less than 10, just remove these samples.

**Comment by blakeliu** [comment]
You are right, after remove all error samples , i can train.
list of error samples:
['train_subset02/LKDS-00150', 
'train_subset13/LKDS-00931', 
'train_subset05/LKDS-00379', 
'train_subset09/LKDS-00648',
 'train_subset12/LKDS-00829',
 'train_subset05/LKDS-00359', 
'train_subset10/LKDS-00684',
 'train_subset07/LKDS-00541', 
'train_subset08/LKDS-00589', 
'train_subset08/LKDS-00598',
 'val_subset01/LKDS-00353', 
'train_subset00/LKDS-00065']

**Comment by blakeliu** [comment]
![_081](https://user-images.githubusercontent.com/9639933/40092840-ffd6e8ac-58f1-11e8-8825-4a63a8859dd7.png)

**Comment by wentaozhu** [comment]
Cool. Congratulations! You get the trained detection model.

**Comment by caslei** [comment]
hi, @blakeliu, would you please share tianchi datastes with me?

**Comment by wentaozhu** [comment]
The used TianChi hold out test set (part of TianChi) used in MICCAI 2018 Weakly supervised detection (https://github.com/wentaozhu/DeepEM-for-Weakly-Supervised-Detection.git) is in https://drive.google.com/drive/folders/1YEnxCtDplTfTp7OVKUGrXy1N8s2YZ7gP?usp=sharing.

**Comment by caslei** [comment]
@wentaozhu thanks a lot for your datasets
