### ISSUE TITLE
FROC value is very low for subset09 LUNA16 dataset

### ISSUE THREAD

**Issue by 91parthparikh** [wentaozhu/DeepLung#151]
Hi,

I am trying reproduce FROC curve for the given LUNA 16 dataset.
Here I am only considering inference part and following below steps before generating FROC curve.

1. Pre-process the dataset using: **python prepare.py**
2. call inference part by using below command:
**python main.py --model dpn3d26 -b 1 --resume /local/lungSegment/DeepLung-master/detector/dpnmodel/fd9044.ckpt --test 1 --save-dir dpn3d26/retrft96X/ --config config_training**

This will store all the boxes in the pbb file.
3. Generate FROC curve: **python frocwrtdetpepchluna16.py** 

**Total number of included nodule annotations: 1186
Total number of nodule annotations: 36378
results_filename /local/lungSegment/New Folder/DeepLung-1-master/detector/results/dpn3d26/retrft96X/bbox/predanno-1.5.csv
frocvalue 0.07949891592387377**

Not sure why this frocvalue is low, can someone point me where things are going wrong ?

************************************************************
CAD Analysis: predanno-1.5
************************************************************

**Candidate detection results:
    True positives: 98
    False positives: 3517
    False negatives: 1088
    True negatives: 0
    Total number of candidates: 4141
    Total number of nodules: 1186
    Ignored candidates on excluded nodules: 513
    Ignored candidates which were double detections on a nodule: 13
    Sensitivity: 0.082630691
    Average number of candidates per scan: 4.663288288**

**Comment by wentaozhu** [comment]
You should generate each fold using the correct model, which means you should infer 10 times for 10 folds. Use the model trained on fold 1-9 for the inference of fold 0. So on, so forth, ...

**Comment by 91parthparikh** [comment]
Thanks @wentaozhu, I will generate output for all the 10 folds (subset0 to subset9) before computing the FROC curve.
