### ISSUE TITLE
How to run frocwrtdetpepchluna16.py?

### ISSUE THREAD

**Issue by SuperInno** [wentaozhu/DeepLung#16]
As we see in frocwrtdetpepchluna16.py  ,results_path is a path of a csv which looks like 3DRes18FasterR-CNN.csv in your directory (in the ./evaluationScript/annotations)  
 But for us ,how to get this csv? 
 I think this csv can be created by function **‘getcsv()’**  in the frocwrtdetpepchluna16.py
but in your code , you comment this function.   

best wishes

HERE IS CODE IN frocwrtdetpepchluna16.py

annotations_filename = './annotations/annotations.csv'# path for ground truth annotations for the fold
annotations_excluded_filename = './annotations/annotations_excluded.csv'# path for excluded annotations for the fold
seriesuids_filename = './annotations/seriesuids.csv'# path for seriesuid for the fold
**results_path** = './'#val' #val' ft96'+'/val'#
sideinfopath = '/media/data1/wentao/tianchi/luna16/preprocess/lunaall/'#subset'+str(fold)+'/'  +str(fold)
datapath = '/media/data1/wentao/tianchi/luna16/lunaall/'#subset'+str(fold)+'/'

**# getcsv(detp, eps)**
def getfroc(detp, eps):

**Comment by wentaozhu** [comment]
Yes. You are right.

getcsv() function gets the predicted csv file. 

I commented it because if you guys wants the results from frocwrtdetpepchluna16.csv I uploaded, uncomment cause overwrite the file.

Thank you very much for your interest!

**Comment by tan416tan** [comment]
hello,I want to know what to fill in results_path.

**Comment by wentaozhu** [comment]
> hello,I want to know what to fill in results_path.

In https://github.com/wentaozhu/DeepLung/blob/master/evaluationScript/frocwrtdetpepchluna16.py
results_path is the --save-dir in https://github.com/wentaozhu/DeepLung/blob/master/run_training.sh
