### ISSUE TITLE
Questions about  ./DeepLung/detector/data.py

### ISSUE THREAD

**Issue by WenJinyu** [wentaozhu/DeepLung#17]
In the file ./DeepLung/detector/data.py, 
    def __len__(self):
        if self.phase == 'train':
            return len(self.bboxes)/(1-self.r_rand)
Why allow data with an index length greater than len(self.bboxes)?
And when idx>=len(self.bboxes), isRand=True. 
   idx = idx%len(self.bboxes)
   bbox = self.bboxes[idx]
   filename = self.filenames[int(bbox[0])]
   imgs = np.load(filename)
   self.crop(imgs, bbox[1:], bboxes,isScale,isRandom)
In the class Crop, why is target set to nan ?
target = np.array([np.nan,np.nan,np.nan,np.nan])

This part I really do not understand.

**Comment by wentaozhu** [comment]
Data augmentation makes the length greater than len(self.bboxes).

if not isRand: # if call crop, isRand is true. This is just for debug purpose.
