### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by a56256324** [wentaozhu/DeepLung#19]
My computer is a single GPU 5 gb of memory And it has been modified batch size, normal worker , epoch, and he sent them is set to 1, the computer operation after a period of time appear the runtime error, and prompt memory errors, graphics configuration is not enough or other reasons?
thanks~

**Comment by a56256324** [comment]
Thank you very much for your help, have a chance to use better GPU, and then to debug your program, and will continue to focus on your medical imaging procedures and paper, thanks again and looking forward to the next.

**Comment by wentaozhu** [comment]
Thank you very much for your interest! Feel free to discuss anything~
