### ISSUE TITLE
about LabelMapping

### ISSUE THREAD

**Issue by zll152** [wentaozhu/DeepLung#20]
Hi， 
when i use my volume （96*96*48）and label to run the “main.py”，i get this error     

”dz = (target[0] - oz[pos[0]]) / anchors[pos[3]]
IndexError: index 4 is out of bounds for axis 0 with size 0”
and the index ，may be 5,6 or 7 in this error。 I have try to print the ”target，oz，anchors ”before run the ”dz = (target[0] - oz[pos[0]]) / anchors[pos[3]]”，but i failed。
meanwhile  I can't understand the details in the LabelMapping function. Could you please explain it?  thanks very much！

**Comment by mowen9** [comment]
I also met the problem.
Have you solved it?
