### ISSUE TITLE
about detection result

### ISSUE THREAD

**Issue by jinmnie** [wentaozhu/DeepLung#22]
hi @wentaozhu, the nodule you detected is more than 130 thousand, but I only got 4 thousand. What's going wrong with the detection? The number worker is 0, The batch size is set to 4. Other parameters are the same with yours.

**Comment by wentaozhu** [comment]
How is the FROC performance difference?

**Comment by jinmnie** [comment]
5 percent lower

**Comment by wentaozhu** [comment]
I used bigger batch size. Try to use 16 or like that in my code and run it on 4 GPUs. The batch size does affect performance.
