### ISSUE TITLE
RuntimeError: inconsistent tensor sizes

### ISSUE THREAD

**Issue by mowen9** [wentaozhu/DeepLung#23]
Hi,
When I run the “main.py”，I get this error:

  File "main.py", line 230, in train
    for i, (data, target, coord) in enumerate(data_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 196, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 119, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 96, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/usr/local/lib/python2.7/dist-packages/torch/functional.py", line 66, in stack
    return torch.cat(inputs, dim, out=out)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2864

It works well when running on LUNA16 dataset. But I get this error when I run on the other dataset.
Could you please explain it? Thanks very much！

**Comment by wentaozhu** [comment]
Could you please provide more information, such as the tensor size of data, target, coord?

**Comment by mowen9** [comment]
@wentaozhu Thanks for your reply.
The tensor size of data, target, coord is 
torch.Size([4, 1, 96, 96, 96])  torch.Size([4, 24, 24, 24, 3, 5])  torch.Size([4, 3, 24, 24, 24])

**Comment by wentaozhu** [comment]
Oh. I see what you mean. The LUNA16 is right. Running on other datasets causes the problem. It may be caused by the data preparation. https://github.com/wentaozhu/DeepLung/blob/master/prepare.py Check the values and do not use the savenpy_luna because you do not lung segmentation.

**Comment by mowen9** [comment]
@wentaozhu 
I don't use your  'prepare.py'.
I use https://github.com/lfz/DSB2017/blob/master/training/prepare.py

**Comment by wentaozhu** [comment]
Check whether there are some invalid values during preparation. I remember we removed some CTs during preparation.

**Comment by mowen9** [comment]
I'm very interested in your work. I want to make a friend with you, may I?
You can send your WeChat or other chat tools to me by email. 
My email address is jianw0921@gmail.com
I will be be more than happy to hear from you.

**Comment by mowen9** [comment]
@wentaozhu 
I find a difference between my preprocessed label and your preprocessed label. 
My z value has a negative value, but your z value is only positive.
For example:
my **_label.npy:
[[  -8.5        107.1171875  222.796875     6.28125  ]]
[[ -21.          94.1640625  187.0078125    3.5015625]]
[[ 101.           82.22265625   22.68164062    3.73828125]]

your  **_label.npy:
[[74.79098309999998 156.65513474000002 71.68981980999999 6.529558333]]
[[84.55161559999999 199.8406053 194.35261574 6.943515582]]
[[202.99999300000002 162.59850287000003 267.57510609999997
  3.8311131889999994]

Does this cause 'inconsistent tensor sizes' error?

**Comment by wentaozhu** [comment]
Yes. You can remove it. Added you.

**Comment by mowen9** [comment]
@wentaozhu Thanks, the problem is solved.
