### ISSUE TITLE
 How to visualize the detected nodules?

### ISSUE THREAD

**Issue by mowen9** [wentaozhu/DeepLung#24]
@wentaozhu 你好！打扰你一下。
如果我想输入一个病人的肺部CT数据，可视化模型输出的结果，即想输出一张带有模型预测出来的结节的图片。
可以根据"ID_pbb.npy"，输出该文件中概率值最大（即p值最大）的那个位置，就是模型预测疑似结节概率最大的那个位置，是这样的吗？

ID_pbb.npy中的数据分别为[p,x,y,z,r]

**Comment by wentaozhu** [comment]
Sorry for the late reply because I am very busy. Now you can check ./DeepLungDetectionDemo/ for detection demo.
