### ISSUE TITLE
Out of memory when test with CUDA_VISIBLE_DEVICES=0,1 python main.py --model res18 -b 2 --resume results/wzy_res18/retrft96$f/00$i.ckpt --test 1 --save-dir wzy_res18/retrft96$f/ --config config_training$f

### ISSUE THREAD

**Issue by codingwolfman** [wentaozhu/DeepLung#25]
process 1 epoch
using gpu 0,1
/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py:24: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
/home/ustc/lclin/dataset/LUNA16/subset9/
/home/ustc/lclin/dataset/LUNA16/subset1/
/home/ustc/lclin/dataset/LUNA16/subset2/
/home/ustc/lclin/dataset/LUNA16/subset3/
/home/ustc/lclin/dataset/LUNA16/subset4/
/home/ustc/lclin/dataset/LUNA16/subset5/
/home/ustc/lclin/dataset/LUNA16/subset6/
/home/ustc/lclin/dataset/LUNA16/subset7/
/home/ustc/lclin/dataset/LUNA16/subset8/
89
results/wzy_res18/retrft960/bbox
(18, 1, 208, 208, 208)
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb5965d14d0>> ignored
Traceback (most recent call last):
  File "main.py", line 389, in <module>
    main()
  File "main.py", line 148, in main
    test(test_loader, net, get_pbb, save_dir, config)
  File "main.py", line 334, in test
    output = net(input,inputcoord)
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ustc/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by wentaozhu** [comment]
From my experience, if you did not change the batch size, you should use 4 GPUs to train. Thank you very much for your interest!

**Comment by codingwolfman** [comment]
when i train ,i was ok,but when i test,error(I use pytorch0.4)
in main.py i set
test_loader = DataLoader(
            dataset,
            batch_size = 1,
            shuffle = False,
            num_workers = args.workers,
            collate_fn = data.collate,
            pin_memory=False)
i thought this was the min batch_size，but still this error...

**Comment by wentaozhu** [comment]
What is your GPU memory for each GPU? and how many GPUs? The warning information is weird. Try to update pytorch and cuda. How many GPU did you use in the training?

**Comment by codingwolfman** [comment]
i use 2 1080ti,total 24G,and i run watch -n 1 nvidia-smi
i see the memory is exhausted for both card,i am really confused about this

**Comment by wentaozhu** [comment]
I know what is your problem. You should crop your imager. 208*208*208 is too big.

**Comment by srinidhigoud** [comment]
The dataset loader crops the images to 96x96x96, isnt it? Even I have the same problem.

**Comment by wentaozhu** [comment]
Yes. Are you using 4 GPUs or smaller batch sizes?

**Comment by srinidhigoud** [comment]
4 GPUs and batch size is 1

**Comment by wentaozhu** [comment]
#39
