### ISSUE TITLE
main.py :TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by shenlinyao** [wentaozhu/DeepLung#26]
When I run the ./detector/main.py, it reports an error when the code runs to line 178. The data I prepared using the script prepare.py. Could you explain why it is ?Thanks! 
```
Traceback (most recent call last):
  File "main.py", line 388, in <module>
    main()
  File "main.py", line 178, in main
    for i, (data, target, coord) in enumerate(train_loader): # check data consistency
  File "C:\Program Files\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "C:\Program Files\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 242, in __init__
    self._put_indices()
  File "C:\Program Files\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 290, in _put_indices
    indices = next(self.sample_iter, None)
  File "C:\Program Files\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "C:\Program Files\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by wentaozhu** [comment]
Are you using your own data? If so, try to convert to LUNA16 format or first use LUNA16 to get a sense of the work, and check the problem is still there.

**Comment by guyucowboy** [comment]
Hi，wentaozhu:
     I meet the same problem. I used pytorch for windows, python3.5.2, anaconda3.  
i, (data, target, coord) in enumerate(train_loader) I change it to i in enumerate(train_loader)
TypeError: 'float' object cannot be interpreted as an integer.  The error is from" for idx in self.sampler:" line 138 in torch\utils\data\sampler.py 
self.sampler is not empty.
![qq 20180909180308](https://user-images.githubusercontent.com/26949256/45263379-f5e0b200-b45a-11e8-9a37-74ee5d534207.jpg)
How to fix it?
Best regards
Gu Yu

**Comment by wentaozhu** [comment]
The same suggestion: Are you using your own data? If so, try to convert to LUNA16 format or first use LUNA16 to get a sense of the work, and check the problem is still there.

Because your dataloader is not correct for your own data. After you finish the LUNA16, you know how to prepare your own data. Thank you very much for your interest!

**Comment by guyucowboy** [comment]
I uesd LUNA16 dataset.  I think that the reason is the difference of division operator"/" between python2 and python3.  But I change some codes to make sure that the data in bbox is integer. 
I will check all the "/" in the prepare.py to make sure that data after processing is the same. 
By the way, could you find where is the difference of the data_source in the figure? 
Best regards
Gu Yu

**Comment by guyucowboy** [comment]
Hi, wentaozhu.
For python3, I change __len__ function in class DataBowl3Detector in the data.py  
  def __len__(self):
        if self.phase == 'train':
            # return len(self.bboxes)/(1-self.r_rand)
            return int(len(self.bboxes) / (1 - self.r_rand))  # change for python3
        elif self.phase =='val':
            return len(self.bboxes)
        else:
            return len(self.sample_bboxes)

Other "TypeError: 'float' object cannot be interpreted as an integer. " for python 3 may be fixed like this.
Best regards
Gu Yu

**Comment by wentaozhu** [comment]
Congratulation!

**Comment by lihaossu** [comment]
@guyucowboy 
Hi, i use luna dataset in Python3 too, and met this error also.
So only change here? I don't need change the divide / in prepare.py any more?
expecting you reply

**Comment by guyucowboy** [comment]
Hi,lihaossu
As I said before, [Other "TypeError: 'float' object cannot be interpreted as an integer. " for python 3 may be fixed like this], you should judge '/' as it different meaning in python2 and python3.
prepare.py should also be changed to fit python3 where integer should be used. You should analyze '/' meaning line by line.
Hope this will help you.
Best regards. 
Gu Yu

**Comment by lihaossu** [comment]
Thank you, I splitted the preprocess part and training part in first phase "detector".  The preprocess seems fine but the training and validation don't work. Do you have the codes for pytorch version > 0.4 ?

**Comment by lihaossu** [comment]
@guyucowboy 
Thank you for your reply, I have splitted it to preprocess part and training part. Preprocessing has completed, but I am stuck in the training phase, do you have codes for pytorch>0.4. I am new for pytorch and confused for these, thank you again

**Comment by lihaossu** [comment]
@guyucowboy 
Anyway, thank you for your reply, I am re-coding this model step by step. Nice to meet you

**Comment by guyucowboy** [comment]
Hi,lihaossu
I wish you success! 
Best regards
Gu Yu

**Comment by lihaossu** [comment]
@guyucowboy 
@wentaozhu 
Hi, My model is in test stage now, I got kaggle DSB 2017 stage 2 but without unzip password, can you share it with me?

**Comment by Minerva-jiezhao** [comment]
> @guyucowboy
> Thank you for your reply, I have splitted it to preprocess part and training part. Preprocessing has completed, but I am stuck in the training phase, do you have codes for pytorch>0.4. I am new for pytorch and confused for these, thank you again

Hi, I did it on pytorch1.0 and python 3.6 smoothly. There are some codes to be changed for high level pytorch. For example, Variable(data.cuda(), requires_grad=True), .data[0] to item().Hope to help you!
