### ISSUE TITLE
problem about frocwrtdetpepchluna16.py

### ISSUE THREAD

**Issue by codingwolfman** [wentaozhu/DeepLung#29]
i decomment getcsv(), then the program had run about one day, i see the _pbb.npy has millions of bboxs, and the program has been doing nms, is this normal? should i modify the detp in frocwrtdetpepchluna16.py? make it higher?

the output is like this
=========================
(torch04) ustc@ustc:~/lclin/code/DeepLung/evaluationScript$ python frocwrtdetpepchluna16.py 
write pbb to csv
ep 1 detp -1.5
88
1.3.6.1.4.1.14519.5.2.1.6279.6001.182192086929819295877506541021_pbb.npy

**Comment by wentaozhu** [comment]
It is the value before exponential function. You can find more in the paper.
