### ISSUE TITLE
The problem with _label.npy

### ISSUE THREAD

**Issue by shenlinyao** [wentaozhu/DeepLung#30]
In the file
https://github.com/wentaozhu/DeepLung/blob/22478e19d593c0669293125747dac52d0c72fd14/prepare.py#L579
the luna annotations.csv's order is x,y,z,diam
but in the file
DeepLung/DeepLungDetectionDemo/detector.ipynb
```
ctdat = np.load('./CT/'+srslst[showid]+'_clean.npy')
ctlab = np.load('./CT/'+srslst[showid]+'_label.npy')
print('Groundtruth')
print(ctdat.shape, ctlab.shape)
for idx in xrange(ctlab.shape[0]):
    if abs(ctlab[idx,0])+abs(ctlab[idx,1])+abs(ctlab[idx,2])+abs(ctlab[idx,3])==0: continue
    fig = plt.figure()
    z, x, y = int(ctlab[idx,0]), int(ctlab[idx,1]), int(ctlab[idx,2])
```
the order is z,x,y.
 Could you tell me where the order has been changed?

**Comment by wentaozhu** [comment]
It is in the function load_itk_image() in prepare.py.
