### ISSUE TITLE
Execution time for frocwrtdetpepchluna16.py

### ISSUE THREAD

**Issue by srinidhigoud** [wentaozhu/DeepLung#32]
How long should it take for frocwrtdetpepchluna16.py file to execute for a single fold and eps of about 100 ? 
I have set the detp at -1. At -1.5 detp, for a single fold, a single eps and 12 nprocesses took about 15 hours, and yet there was no single result. Is this normal?

**Comment by srinidhigoud** [comment]
Can you give a rough idea, how long it took for you?

**Comment by wentaozhu** [comment]
One day for 100 epochs is tolerable.

**Comment by srinidhigoud** [comment]
Hi, also I could not find /media/data1/wentao/LIDC-IDRI/list3.2.xls in extclsshpinfo.py, in my LIDC dataset. Is this the file at DeepLung/nodcls/data/list3.2.csv?

**Comment by wentaozhu** [comment]
Yes. It is the same file. It seems you are trying to run the classification part. Congratulation!

**Comment by srinidhigoud** [comment]
Great! Thank you
