### ISSUE TITLE
Questions about training batches

### ISSUE THREAD

**Issue by anruoxi123** [wentaozhu/DeepLung#35]
Hello, teacher:

Recently running DeepLung project, the following problems occurred:
RuntimeError: cuda runtime error (2) : out of memory at /b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu:66
It can be seen from the data that the GPU memory is too small, so it is recommended to reduce the training times. I want to ask you, where do you look for these variables?

**Comment by wentaozhu** [comment]
What is your GPU memory size? You can reduce the batch size. I used 4 Titan 1080 TI for training.

**Comment by anruoxi123** [comment]
I don't know what my GPU configuration is, I changed maxeps=150 in run_training.sh file to 10, or the above error will still occur. I see your original configuration is 6 gpus, I only have two gpus, and I have reduced the data set. If I still report an error, where should I change?

**Comment by wentaozhu** [comment]
Try to reduce the batch size.

**Comment by anruoxi123** [comment]
Teacher, after research, I found that the memory of my machine is not enough to run the run_training.sh file. I want to run the classification section directly. That is to say, directly skip detection and use data to train classification network. If so, which file in the nodcls folder is the entry file? Thank you for your advice.

**Comment by wentaozhu** [comment]
This is for nodule classification. ./nodcls/main_nodcls.py
