### ISSUE TITLE
run frocwrtdetpepchluna16.py with tianchi dataset

### ISSUE THREAD

**Issue by leowangzi** [wentaozhu/DeepLung#36]
The Tianchi dataset did not generate *_extendbox.npy in prepare.py.
in frocwrtdetpepchluna16.py, the convertcsv function need to load *_extendbox.npy and do some matrix operations like this:
```
Pbb[:, 1:] = np.array(pbb[:, 1:] + np.expand_dims(extendbox[:,0], 1).T)
Pbb[:, 1:] = np.array(pbb[:, 1:] * np.expand_dims(resolution, 1).T / np.expand_dims(spacing, 1).T)
```
How to deal with this step? thanks.

**Comment by wentaozhu** [comment]
frocwrtdetpepchluna16.py is to calculate the FROC. You need first train the model, then test. Then calculate the FROC. prepare.py is the pre-processing.

**Comment by leowangzi** [comment]
@wentaozhu 
I have finished the training and the test. I met the above problems when calculating FROC.

**Comment by leowangzi** [comment]
![newplot](https://user-images.githubusercontent.com/395896/46116854-9fcc8680-c230-11e8-9baa-708553292690.png)

**Comment by leowangzi** [comment]
![default](https://user-images.githubusercontent.com/395896/46116912-f639c500-c230-11e8-8b71-05de4b21b012.png)

**Comment by wentaozhu** [comment]
Your loss curve seems weird. Maybe you can first try Luna 16.
