### ISSUE TITLE
test阶段出现了 out of memory

### ISSUE THREAD

**Issue by harris0704** [wentaozhu/DeepLung#37]
python main.py --model dpn3d26 --test 1 --config 'config_training2'

![image](https://user-images.githubusercontent.com/36401652/46652559-fc875400-cbd5-11e8-8309-bc31b79c2d62.png)

**Comment by wentaozhu** [comment]
What is the image size? Did you pro-process the images?

**Comment by harris0704** [comment]
> What is the image size? Did you pro-process the images?

我只有一块1070TI，我使用了你的数据预处理代码，并且完成了train。
但是在test的时候总是会出现out of memory。- -.
这是为什么呢

**Comment by harris0704** [comment]
谢谢！我已经解决了

**Comment by wentaozhu** [comment]
It may be caused by not pre-processing the test image. Try to pre-process (crop) the test image.

**Comment by wentaozhu** [comment]
@harris0704 how did you handle the bug? #39

**Comment by harris0704** [comment]
I  just modify the  --n_test， and it works

**Comment by harris0704** [comment]
I have pre-processed all the data, contian train and test image
