### ISSUE TITLE
About the running time

### ISSUE THREAD

**Issue by anruoxi123** [wentaozhu/DeepLung#38]
During the detection phase, 50 training batches were set up by running the run_training.sh file, and the program was stuck in the following interface.

I want to ask, what is this program used for, because I only use two gpus, is the program itself needs time, or is the program stuck here?
![d44381a8cb38911dd6c5909d32ee6a4](https://user-images.githubusercontent.com/43407427/46706720-94ce1900-cc68-11e8-9299-1ec189fdbf07.png)
![fd894ff92a3f1c312d80d472abcec04](https://user-images.githubusercontent.com/43407427/46706723-9bf52700-cc68-11e8-85cc-ff6c9e36095d.png)

**Comment by wentaozhu** [comment]
You can check the GPU, CPU, memory use of the process. Maybe it is because the model is not well trained and the number of proposals is too big. I have two suggestions: 1 check which line is the code stuck 2 use 150 epochs to get a good model.

**Comment by anruoxi123** [comment]
I want to ask, what is the function of the following code, can I remove it? My program will be stuck here when it runs.
![fd894ff92a3f1c312d80d472abcec04](https://user-images.githubusercontent.com/43407427/46785426-4ef67b00-cd64-11e8-90ff-07cb68719156.png)

**Comment by wentaozhu** [comment]
It is test for the saved models.

**Comment by wentaozhu** [comment]
If you do not want to test and just want to get the trained model, you can definitely comment them.
