### ISSUE TITLE
Out of memory when test with CUDA_VISIBLE_DEVICES=0,1 python main.py --model res18 -b 2 --resume results/wzy_res18/retrft96$f/00$i.ckpt --test 1 --save-dir wzy_res18/retrft96$f/ --config config_training$f

### ISSUE THREAD

**Issue by jehovahxu** [wentaozhu/DeepLung#39]
i also found the problem when i train ,i was ok,but when i test,error(I also use pytorch0.4)
i saw your [issue](https://github.com/wentaozhu/DeepLung/issues/31) and found that split combiner brings the image size to 208 and it split in mian.py and data.py
but i don't know how to fix it 
how do you do about it @srinidhigoud

**Comment by jehovahxu** [comment]
there are six issue about out of memory in test but no solution

**Comment by wentaozhu** [comment]
I have one easy suggestion. First, process the training and test at the same time. If you do not have test label, you can use fake label to generate the processed data. Second, do the data separation and write the file list into the configuration file. Third, run the .sh for training and test after. This is exactly I do on LUNA16 and Tianchi dataset.

**Comment by jehovahxu** [comment]
thank you so much for your reply. I processed the LUNA16 dataset with  prepare.py . I debug the project, when test ,（data.py） the dataloader load processed data(subset9)，but the function split_combine.split processed the image to 208*208*208 without crop . I tried use the train_dataloader to continue the project，the size of image is right but can't got nzhw. I    follow readme.md and I am not clear whether I processed the dataset in a wrong way

**Comment by wentaozhu** [comment]
Check these file paths consist all the luna files.
luna_segment = config['luna_segment']
savepath = config['preprocess_result_path']
luna_data = config['luna_data']
luna_label = config['luna_label']

**Comment by jehovahxu** [comment]
i checked the config file and it's all consisted all the luna files, and the path is right.
i just debug the project. in data.py when self.phase != 'test' , the size of  imgs=np.load(filename) is  1*263*181*247, and return by the function of self.crop() the size change to 1*96*96*96.  
but in the else (self.phase == 'test') , the size of imgs=np.load(filename) is 1*263*181*47, and through the np.pad() , the size of imgs change to 1*264*184*284, but the funtction self.split_comber.split(imgs) returns the imgs size 8*1*208*208*208 
so i think it is not my about to preprocess the dataset, there are some details may be ignored

**Comment by wentaozhu** [comment]
How about putting all the data into the training and preprocessing them first by revising DeepLung/config_training.py? Put all the data into the 'train_data_path'.

**Comment by jehovahxu** [comment]
i changed the value of  margin and sidelen to split test data size , and it worked

**Comment by wentaozhu** [comment]
It seems strange because I did not have the problem. @jehovahxu  changed main.py line 126 to
margin = 0
sidelen = 96
and it worked. 
In the data.py, class Crop() used crop size as 96. I do not why.

**Comment by jehovahxu** [comment]
@harris0704 It is invalid for reducing the data size. i have 2 titan GPUs, and  I tried your method but the size of data is still 208×208*208 and also out of memory. I still think the value of margin and sidelen influenced the data size.

**Comment by caslei** [comment]
@jehovahxu  Hi, I have the same issue as yours. I can run main.py to test 'subset9', but the results may be wrong since the prediction is empty

![image](https://user-images.githubusercontent.com/10126763/49916272-3429ab00-fe68-11e8-85f9-b620a3c90a5c.png)

**Comment by wentaozhu** [comment]
Just use one sample for each GPU. That is, try to reduce the batch size.

**Comment by wentaozhu** [comment]
> @jehovahxu Hi, I have the same issue as yours. I can run main.py to test 'subset9', but the results may be wrong since the prediction is empty
> 
> ![image](https://user-images.githubusercontent.com/10126763/49916272-3429ab00-fe68-11e8-85f9-b620a3c90a5c.png)

Try to use smaller detection probability.
