### ISSUE TITLE
about data extract in nodclsgbt.py

### ISSUE THREAD

**Issue by codingwolfman** [wentaozhu/DeepLung#41]
cropdata = np.ones((CROPSIZE, CROPSIZE, CROPSIZE))*170
 	cropdatatmp = np.array(data[0, bgx:bgx+CROPSIZE, bgy:bgy+CROPSIZE, bgz:bgz+CROPSIZE])
 	cropdata[CROPSIZE/2-cropdatatmp.shape[0]/2:CROPSIZE/2-cropdatatmp.shape[0]/2+cropdatatmp.shape[0], \
 	    CROPSIZE/2-cropdatatmp.shape[1]/2:CROPSIZE/2-cropdatatmp.shape[1]/2+cropdatatmp.shape[1], \
 	    CROPSIZE/2-cropdatatmp.shape[2]/2:CROPSIZE/2-cropdatatmp.shape[2]/2+cropdatatmp.shape[2]] = np.array(2-cropdatatmp)
i have two questions
1.why 2-cropdatatmp?
2.CROPSIZE/2-cropdatatmp.shape[0]/2 obviously equals to zero?

**Comment by wentaozhu** [comment]
1 Could you please help me check the range of data = np.load(os.path.join(preprocesspath, pid+'_clean.npy'))
2 Sometimes the shape of data is smaller than bgx+CROPSIZE, bgy+CROPSIZE, bgz+CROPSIZE

**Comment by codingwolfman** [comment]
oh, the range of data is enough for cropsize, i didn't realize numpy is ok when out of range.
but , i still don't understand why you use 2-cropdatatmp to fill the cropdata, and i think cropdatatmp=np.array(data[0,bgx:crdx+cropsize/2,bgy:crdy+cropsize/2,bgz:crdz+cropsize/2) may be better

**Comment by codingwolfman** [comment]
x ： 117 378
y：  160 392
z：  168 400

**Comment by wentaozhu** [comment]
I think it should be np.array(cropdatatmp), not np.array(2-cropdatatmp)

It should not affect the GBT results because tree classifier is not affected by input range. Maybe you can get better results after changing it.
