### ISSUE TITLE
os.popen('stty size', 'r').read().split()

### ISSUE THREAD

**Issue by NotMatter** [wentaozhu/DeepLung#44]
Hello, in the 45th row of  DeepLung/nodcls/utils.py  : _, term_width = os.popen('stty size', 'r').read().split()。The version of my python is 3.6, the error will occur if it runs：ValueError: not enough values to unpack (expected 2, got 0). I try to print(os.popen('stty size', 'r').read())，but the output is 'stty' ����...Can you help me ? Many thanks.

**Comment by wentaozhu** [comment]
How about using anaconda Python 2?

**Comment by NotMatter** [comment]
> How about using anaconda Python 2?

My Python is 3.6. Many thanks for your reply. Best wishes.
