### ISSUE TITLE
when i run ./detector/main.py i find this error

### ISSUE THREAD

**Issue by sunhaotian130911** [wentaozhu/DeepLung#45]
the output of terminal:
CUDA_VISIBLE_DEVICES=0,1 python main.py --model dpn3d26 -b 32   --save-dir res18/retrft969/ --epochs 150 --config config_training9

using gpu 0,1
/home/amax/.local/lib/python2.7/site-packages/torch/cuda/__init__.py:114: UserWarning: 
    Found GPU0 TITAN V which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
/home/amax/.local/lib/python2.7/site-packages/torch/cuda/__init__.py:114: UserWarning: 
    Found GPU1 TITAN V which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
/home/amax/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py:24: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 0 which
    has less than 75% of the memory or cores of GPU 1. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
['/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset0/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset1/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset2/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset3/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset4/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset5/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset6/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset7/', '/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset8/']
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset0/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset1/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset2/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset3/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset4/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset5/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset6/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset7/
/media/amax/BC1259BD12597D78/sunhaotian/luna16/dataset/subset8/
800
800
88
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL Error 1: unhandled cuda error
已放弃 (核心已转储)

my gpus are 2 nvidia titian v ,total memory is 24g,should i install cuda 9?

**Comment by wentaozhu** [comment]
You can have a try!
