### ISSUE TITLE
Problems in nodules classification.

### ISSUE THREAD

**Issue by NotMatter** [wentaozhu/DeepLung#46]
Hello, can I only run the code in “nodcls” to complete the benign or malignant classification without detection results. Because I only want to accomplish the diagnosis task.

**Comment by wentaozhu** [comment]
1 For pure nodule classification task, you can use the ROI for classification
2 For classification based on detection, you can use the pertained detection models https://github.com/wentaozhu/DeepLung/tree/master/detector/resmodel to get the nodule detection results, that is nodule ROI for classification.

**Comment by NotMatter** [comment]
Thank you so much for your reply. Here is my workflow: the folder “lunaall” contains 888 preprocessed CTs from LUNA16, after the operation of “crop”, the folder “crop_v3” contains 1004 VOIs. The information of “seriesuid, coordX, coordY, coordZ, diameter_mm, malignant” are extracted from “annotationdetclsconvfnl_v3.csv”. Then, the nodule diagnosis can be completed according to your codes in “main_nodcls.py”? Many thanks.

**Comment by NotMatter** [comment]
> 1 For pure nodule classification task, you can use the ROI for classification
> 2 For classification based on detection, you can use the pertained detection models https://github.com/wentaozhu/DeepLung/tree/master/detector/resmodel to get the nodule detection results, that is nodule ROI for classification.

Thank you so much for your reply. Here is my workflow: the folder “lunaall” contains 888 preprocessed CTs from LUNA16, after the operation of “crop”, the folder “crop_v3” contains 1004 VOIs. The information of “seriesuid, coordX, coordY, coordZ, diameter_mm, malignant” are extracted from “annotationdetclsconvfnl_v3.csv”. Then, the nodule diagnosis can be completed according to your codes in “main_nodcls.py”? Many thanks.

**Comment by 3learning12340** [comment]
> > 1 For pure nodule classification task, you can use the ROI for classification
> > 2 For classification based on detection, you can use the pertained detection models https://github.com/wentaozhu/DeepLung/tree/master/detector/resmodel to get the nodule detection results, that is nodule ROI for classification.
> 
> Thank you so much for your reply. Here is my workflow: the folder “lunaall” contains 888 preprocessed CTs from LUNA16, after the operation of “crop”, the folder “crop_v3” contains 1004 VOIs. The information of “seriesuid, coordX, coordY, coordZ, diameter_mm, malignant” are extracted from “annotationdetclsconvfnl_v3.csv”. Then, the nodule diagnosis can be completed according to your codes in “main_nodcls.py”? Many thanks.

hello, how did you finish the crop process? looking forward to your reply
