### ISSUE TITLE
Hi, I have two questions: (1) why are 'val_data_path' and 'test_data_path' in config_training.py the same? Generally, they should be different. (2)  due to limited GPU memory, I used a for loop to replace '_=pool.map(partial_savenpy_luna,range(N)' with 'savenpy_luna(id=0, annos=annos, filelist=[single_file],....)' in prepare.py. However, I could get two '_clean.npy' results with the same filename but different image shape (e.g., [1,342,275,315] and [1,342,278,315])'. Are there some advices about the phenomenon？

### ISSUE THREAD

**Issue by caslei** [wentaozhu/DeepLung#48]

**Comment by caslei** [comment]
two '_clean.npy' results  were generated by '**_=pool.map(partial_savenpy_luna,range(N)**' and '**savenpy_luna(id=0, annos=annos, filelist=[single_file],....)**'

**Comment by wentaozhu** [comment]
I suggest, first run the standard cross validation. After you succeed, try to do more tasks. We have already validated the generalization ability on hold out test dataset in "Zhu, Wentao, Yeeleng S. Vang, Yufang Huang, and Xiaohui Xie. "DeepEM: Deep 3D ConvNets With EM For Weakly Supervised Pulmonary Nodule Detection." MICCAI (2018). https://github.com/wentaozhu/DeepEM-for-Weakly-Supervised-Detection"

**Comment by caslei** [comment]
hi @wentaozhu , I have solved this issue!
This issue is due to the difference of patch sizes in training ([96]*3) and testing ([sidelen+2*margin]*3) procedures.
