### ISSUE TITLE
Regarding humanclassification.py and nodclsgbt.py.

### ISSUE THREAD

**Issue by abhishek795jha** [wentaozhu/DeepLung#49]
Hi, need your help with these:
1. 85.04% accuracy for nodule classification using GBM, nodule diameter and pixel. According to paper, you are able to achieve 86.12%.
2. Not able to generate doctor's performance using humanclassification.py. Value of ntot and nacc does not change (value is 0).

Can you list out the probable reasons for these results?

**Comment by wentaozhu** [comment]
I think the results are pretty close. How about tune the parameters of GBM?

You may print out the results after each section in the code so that you can get to know where is wrong.
