### ISSUE TITLE
Could you please explain the PATH in those config files clearly?

### ISSUE THREAD

**Issue by TracelessLe** [wentaozhu/DeepLung#5]
In config_training0(~9).py under the master folder, some data paths are given. But I'm a littele confused about the difference among the 10 files, for example:
in config_training0.py, 'train_preprocess_result_path':

> '/media/data1/wentao/tianchi/luna16/preprocess/';

but in config_training1.py, 

> 'train_preprocess_result_path':'/media/data1/wentao/tianchi/luna16/preprocess/lunaall/'.

I wonder why the paths are different while the subsets of LUNA16 dataset has equal position?
Moreover, for the bbox_path, why val & test bbox_paths are different between the train_bbox_path?
such as in config_training4.py:

> 'train_bbox_path':'/media/data1/wentao/tianchi/bbox/train/',  
> 'val_bbox_path':'/media/data1/wentao/tianchi/val/',  
> 'test_bbox_path':'/media/data1/wentao/tianchi/test/', 

These paths are important for training, would you please share some time to explain your consideration?

**Comment by wentaozhu** [comment]
I am attending the WACV conference now. Will update a brief new version with detailed explanation a couple days later.

**Comment by TracelessLe** [comment]
It's okay. Thank you!

**Comment by wentaozhu** [comment]
You can use config_training0.py. I add some explanations which should be easy to use.
