### ISSUE TITLE
Question about the dpn3d26.py

### ISSUE THREAD

**Issue by TracelessLe** [wentaozhu/DeepLung#54]
Thanks for your excellent work. I have a question about the CNN "dpn3d26". In the "class DPN(nn.Module)",  between the self.layer5 and self.layer6, the self.last_planes is equal to 224+3, what is the means of the '3'?

![360 16241225839879](https://user-images.githubusercontent.com/22371026/51154348-73577b80-18ae-11e9-9642-82b3858efb2d.png)

**Comment by wentaozhu** [comment]
Thank you very much for your interest!

It is the hyper-parameter in the DPN.

If you want to know more about it, you can set debug=True to print out the shape of blocks in DPN https://github.com/wentaozhu/DeepLung/blob/master/detector/dpn3d26.py

**Comment by TracelessLe** [comment]
Thanks a lot, I have found that it is related with the "coord".
