### ISSUE TITLE
questions about testing in classification

### ISSUE THREAD

**Issue by NotMatter** [wentaozhu/DeepLung#55]
Hello, sorry to disturb you again. I used the ROI for pure nodule classification task. 

After training, which ***.py I should to use to test the trained model? From “README”, I found the “testdet2cls.py” is used to test the trained model, but it might based on detection, because the“testdet2cls.py” running with “pbb.npy”, and there were no “pbb.npy” occurred during training in classification stage. 

Thanks a lot, waiting for your reply.
![image](https://user-images.githubusercontent.com/42600942/51165273-a44da580-18da-11e9-8fa1-1d9999fa4467.png)

**Comment by wentaozhu** [comment]
For classification using DPN, use the code in main_nodcls.py. I am very sorry for the mistake.

**Comment by NotMatter** [comment]
> For classification using DPN, use the code in main_nodcls.py. I am very sorry for the mistake.

Many thanks. That is to say: no ***.py is used to test the trained model in classification? the classification results were obtained from main_nodcls.py?

**Comment by wentaozhu** [comment]
I think so because we can also get the GBT results from main_nodcls.py. Good Luck!
