### ISSUE TITLE
where can i find annotationdetclsgt.csv?

### ISSUE THREAD

**Issue by dyther** [wentaozhu/DeepLung#56]
As I want to run main_nodcls.py ,I need to generate crop_v3 through nodclsgbt.py,but it need annotationdetclsconv_v3  ，so I want to run dataconverter.py ,but it need annotationdetclsgt.csv.
And I don't know how to get it .
 if I did something wrong ?could you please tell me how to get the annotationdetclsgt.csv?

**Comment by wentaozhu** [comment]
annotationdetclsconvfnl_v3.csv is annotationdetclsconv_v3.csv you needed for nodclsgbt.py

If you want to know how to extract nodule information, you can use extclsshpinfo.py
