### ISSUE TITLE
about training epochs and lr in nodule classification

### ISSUE THREAD

**Issue by NotMatter** [wentaozhu/DeepLung#57]
Sorry to disturb you again. Can you tell me the criterion that you adopted when you set the number of epochs and related lr in your paper? (epoch 0-525 lr 0.01,  epoch 526-840 lr 0.001, epoch 840-1050 lr 0.0001) Many thanks for your reply.

**Comment by wentaozhu** [comment]
I think the performance is not sensitive to the schedule. Thank you very much for your interest!

**Comment by NotMatter** [comment]
> I think the performance is not sensitive to the schedule. Thank you very much for your interest!

Thanks for your reply. Thank you.
