### ISSUE TITLE
about

### ISSUE THREAD

**Issue by anruoxi123** [wentaozhu/DeepLung#58]

**Comment by anruoxi123** [comment]
I have a question about the detection part of the code.

Test ==1, margin = 32, sidelen = 144 in main.py file.

Now I have changed the network structure, and the training part is completed successfully.

However, when it comes to the test section, it reminds me that the dimensions do not match.

I want to think about it, it is only this parameter may have a problem, also look for advice.
![cf38c02fbd66914e179ad4e304352c3](https://user-images.githubusercontent.com/43407427/51656570-98e63280-1fdc-11e9-9e9e-55a1834e29f1.png)

**Comment by wentaozhu** [comment]
I am very sorry that I do not understand your problem. Did you firstly run the training and testing of DeepLung code successfully?

**Comment by anruoxi123** [comment]
Yes, I have run through the source code,

After running through, I made some changes to the network structure and added some convolutional layers.

The training part can be completed successfully, but when it comes to the test part, the following errors will occur.

I would like to ask, is the input image size of the test part also 96*96*96?

**Comment by wentaozhu** [comment]
Yes. I think so. Maybe you can crop the image and run through the test part then, Good luck~

**Comment by anruoxi123** [comment]
Ok, thanks for your comments.
