### ISSUE TITLE
deeplung

### ISSUE THREAD

**Issue by mrzhangzizhen123** [wentaozhu/DeepLung#59]
您好，有幸读到您发表的集肺结节检测和诊断于一体的文章。我在复现Deeplung中，检测部分代码，训练验证正常跑通，进入测试代码就报内存溢出。测试输入大小是，torch.size(18,1,208,208,208]这个有问题吗？希望您能给与帮助，非常感谢您。

**Comment by wentaozhu** [comment]
https://github.com/wentaozhu/DeepLung/issues/37

**Comment by wentaozhu** [comment]
Please read all these reported issues. I am pretty sure there are some solutions for the exactly same issue.

Including this repository https://github.com/uci-cbcl/DeepLung.git
