### ISSUE TITLE
Inference produces millions of bounding boxes

### ISSUE THREAD

**Issue by QuantScientist** [wentaozhu/DeepLung#6]
Dear team,
I am trying to run inference, I did NOT train the detector, I used the CHK files that you provided. For instance, chk064 or  res18fd9020.ckpt  which is under  `detector/dpnmodel/` and `detector/resmodel/` were used like so:
```
#!/bin/bash
set -e

# python prepare.py
cd detector
maxeps=2
f=9
CUDA_VISIBLE_DEVICES=0,1

/usr/bin/python3.5 main.py --model res18 -b 4 --resume res18fd9020.ckpt --test 1 --save-dir res18/retrft96$f/ --epochs $maxeps --config con
fig_training$f
```

1. Is this the correct way to run inference? if not can you please indicate how to properly do it? 
2. Why do the resulting PBB and LBB contain millions of bounding boxes? is that because the CHK files mentioned above are not good enough? 

Many thanks,

**Comment by wentaozhu** [comment]
LBB is the ground truth, which should be not have too many bounding boxes. For PBB, we typically use threshold to remove bounding boxes of small probabilities. After that, we use NMS to further reduce some overlapped bounding boxes. You can find them in the evaluationScript/frocwrtdetpepchluna16.py

**Comment by QuantScientist** [comment]
Thanks, 
While running training using:
```
#!/bin/bash
set -e

# python prepare.py
cd detector
maxeps=150
f=9
CUDA_VISIBLE_DEVICES=0,1

/usr/bin/python3.5 main.py --model res18 -b 4  --save-dir res18/retrft96$f/ --epochs $maxeps --config config_training$f

```
I get:
`RuntimeError: dimension specified as -1 but tensor has no dimensions`

The faulty line is here:
```
def hard_mining(neg_output, neg_labels, num_hard):
    print('neg_output: {}'.format(len(neg_output)))
    print('num_hard: {}'.format((num_hard)))

    _, idcs = torch.topk(neg_output, min(num_hard, len(neg_output)))
    neg_output = torch.index_select(neg_output, 0, idcs)
    neg_labels = torch.index_select(neg_labels, 0, idcs)
    return neg_output, neg_labels
```

Full stack:
```
Train phase
Batch size: 4
neg_output: 0
num_hard: 8
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main()
  File "main.py", line 212, in main
    train(train_loader, net, loss, epoch, optimizer, get_lr, args.save_freq, save_dir)
  File "main.py", line 234, in train
    loss_output = loss(output, target)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shlomo/db/dev/baidu-2018/detector/layers.py", line 182, in forward
    neg_output, neg_labels = hard_mining(neg_output, neg_labels, self.num_hard * batch_size)
  File "/home/shlomo/db/dev/baidu-2018/detector/layers.py", line 153, in hard_mining
    _, idcs = torch.topk(neg_output, min(num_hard, len(neg_output)))
RuntimeError: dimension specified as -1 but tensor has no dimensions

```

**Comment by QuantScientist** [comment]
Hi,
I understand that For PBB, you use threshold to remove bounding boxes of small probabilities and after that you use NMS to further reduce some overlapped bounding boxes. however, even running NMS on a single PBB take few hours and it does not finish. 

Is this the expected behavior? 
How come each BB has 2.5 Million entries? 

Thanks!

**Comment by wentaozhu** [comment]
You need to first remove box with small probability, that is detp in ./evaluationScript/frocwrtdetpepchluna16.py 

If there are many boxes left, try to use bigger detp. 

After it, use NMS. If there are many boxes left before NMS, you need to increase your threshold for removing boxes.

**Comment by wentaozhu** [comment]
For your last question, I have told you to debug and check #4

**Comment by blakeliu** [comment]
@wentaozhu curious!!!  

In  code ./evaluationScript/frocwrtdetpepchluna16.py, function convertcsv
what is the range of the pbb[pbb[:,0]? How can i decide detp value?

**Comment by wentaozhu** [comment]
Typically, you can set as -2, -1.5 or -1
