### ISSUE TITLE
Questions about data augmentation

### ISSUE THREAD

**Issue by isihkr** [wentaozhu/DeepLung#60]
HI! I have some questions here：
Is function augment(...) in data.py working? I've set breakpoints but it seems not working.Could you please tell me How can i use this function?
Looking forward to your reply!
@wentaozhu

**Comment by wentaozhu** [comment]
I think the code is using augment(...) in https://github.com/wentaozhu/DeepLung/blob/master/detector/data.py

First it uses the ground truth box. Then use augmented ground truth box.

**Comment by lihaossu** [comment]
@wentaozhu 
@isihkr 
Hi, my model is in test stage, I got kaggle stage 2 dataset without unzip password, can someone share with me? thank you!
