### ISSUE TITLE
Question in data.py at setting target's value when isRand is true

### ISSUE THREAD

**Issue by zhangfb** [wentaozhu/DeepLung#62]
In ./DeepLung/detector/data.py, at line 206, you set `target = np.array([np.nan,np.nan,np.nan,np.nan])`. In my understanding, this line is executed when isRandomImg is true, which means that you randomly sample a file and then randomly crop a part of it. So setting target to np.nan means that you think the randomly cropped volume will not contain a bounding box. But there are chances that the randomly cropped volume does contain bounding boxes. Is it a bug or I don't understand the codes correctly?

![image](https://user-images.githubusercontent.com/34835701/54805183-1ebaed00-4cb1-11e9-92f1-b41ff2b9bdde.png)

**Comment by wentaozhu** [comment]
isRand is True in the training. We only use the box in the training.

In the test, we predict the target. Thus there is no bug.

**Comment by zhangfb** [comment]
But in the **LabelMapping**, if the target is **np.nan**, the label without positive points are returned. Won't this neglecting influence the performance?
![image](https://user-images.githubusercontent.com/34835701/54862380-e381f200-4d74-11e9-9dc7-423bd6751c8d.png)

And I have another question in the LabelMapping assigning the positive points. I understand that the function of codes in the picture below is to assign positive points where the IOU of target bbox between nearby points' anchors are greater than th (0.5 in training). And here is **a sampling process** which only samples **one positive point** out if there are several points satisfying the IOU limitation.  So I don't know why there must have a sample process ensuring only one positive point existing. Won't it be better for training if there are more positive points? 

![image](https://user-images.githubusercontent.com/34835701/54862452-1d072d00-4d76-11e9-8599-96e6ce8e12d3.png)

**Comment by wentaozhu** [comment]
For test, we are predicting the box and there is no impact on the model.

You may have a try and check the performance gain.

**Comment by zhangfb** [comment]
Thank you for your answers!
