### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by zp678** [wentaozhu/DeepLung#63]
Hello, your model is Faster RCNN. I want to know what part of your RPN network is. Thank you.

**Comment by wentaozhu** [comment]
Actually, we only use RPN model because we only have the lesion of one category in the task.

**Comment by zp678** [comment]
Thank you for your reply. May I understand that the structure(only RPN) is similar to one-stage mode，such as ssd？Looking forward to your reply
Sent from Mail for Windows 10

**Comment by wentaozhu** [comment]
Yes. Good luck!
