### ISSUE TITLE
reproducing deeplung

### ISSUE THREAD

**Issue by melody-rain** [wentaozhu/DeepLung#64]
Could anyone reproduce the author's result?

I trained the model according to this repo with training data of luna subset 0~8 and test the model regarding luna subset 9 as the testing data.

By changing below to avoid GPU OOM:
```
margin = 16 # 32
sidelen = 144 # 144
```
my testing result is similar to this:
```
************************************************************
CAD Analysis: predanno-2d3
************************************************************

Candidate detection results:
    True positives: 69
    False positives: 1918
    False negatives: 1117
    True negatives: 0
    Total number of candidates: 2346
    Total number of nodules: 1186
    Ignored candidates on excluded nodules: 357
    Ignored candidates which were double detections on a nodule: 2
    Sensitivity: 0.058178752
    Average number of candidates per scan: 2.641891892
```

Even though I use the provided model to test,
```
res18fd0008.ckpt
res18fd1049.ckpt
res18fd2020.ckpt
res18fd3006.ckpt
res18fd4143.ckpt
res18fd5097.ckpt
res18fd6028.ckpt
res18fd7024.ckpt
res18fd8014.ckpt
res18fd9020.ckpt
```
 I just got poor sensitivity which is less than 0.1.

So have anyone reproduced the paper? Thanks.

**Comment by wentaozhu** [comment]
Many researchers have reproduced the work. You may read the previous issues to solve the OOM. If you have results, please reply here so that we can help ours. Thanks!

**Comment by melody-rain** [comment]
@wentaozhu 

I forgot to combine the detection csvs into one. After combining, I got similar results to your paper.

Thanks.

**Comment by MrWeiminlee** [comment]
Do you got get 1-fold performance by  concatenating the result csvfiles which are in the 150 val?Or you concatenated the 10 csvfiles which are the results of all 10-fold in every val150 file to get the fina performance?

**Comment by wentaozhu** [comment]
later one
