### ISSUE TITLE
怎么训练？

### ISSUE THREAD

**Issue by DyerLee** [wentaozhu/DeepLung#66]
你好，打扰了。我是在windows下的环境，你这些代码的一个运行顺序是怎样的？.sh我需要运行吗？数据处理完 我要怎么训练？谢谢

**Comment by wentaozhu** [comment]
需要配置 pytorch Windows环境

**Comment by DyerLee** [comment]
你好，打扰了。请问一下代码中的run_training.sh这个代码是什么？怎么运行?

发送自 Windows 10 版邮件应用

发件人: Wentao Zhu
发送时间: 2019年4月4日 1:33
收件人: wentaozhu/DeepLung
抄送: DyerLee; Author
主题: Re: [wentaozhu/DeepLung] 怎么训练？ (#66)

Closed #66.

**Comment by wentaozhu** [comment]
.sh is executive script.
