### ISSUE TITLE
main.py stuck

### ISSUE THREAD

**Issue by MrWeiminlee** [wentaozhu/DeepLung#67]
I have use 2  GTX 1080 Ti ,When I run sh run_traininig.sh, 

using gpu 0,1
['../../../data/luna16/data/subset0/', '../../../data/luna16/data/subset1/', '../../../data/luna16/data/subset2/', '../../../data/luna16/data/subset3/', '../../../data/luna16/data/subset4/', '../../../data/luna16/data/subset5/', '../../../data/luna16/data/subset6/', '../../../data/luna16/data/subset7/', '../../../data/luna16/data/subset8/']
../../../data/luna16/data/subset0/
../../../data/luna16/data/subset1/
../../../data/luna16/data/subset2/
../../../data/luna16/data/subset3/
../../../data/luna16/data/subset4/
../../../data/luna16/data/subset5/
../../../data/luna16/data/subset6/
../../../data/luna16/data/subset7/
../../../data/luna16/data/subset8/
800
800
here
88
there

it seems the program is stuck in 

    print("there")
    for i, (data, target, coord) in enumerate(train_loader): # check data consistency
        if i >= len(trainfilelist)/args.batch_size:
            break

    for i, (data, target, coord) in enumerate(val_loader): # check data consistency
        if i >= len(valfilelist)/args.batch_size:
            break
    print("there1")

I have changed the batch_size from 16 to 1,but it doesn't work .it also stuck here,do you know what is wrong? How could I fix it?

**Comment by wentaozhu** [comment]
How many minute did you wait? Maybe it was processing. Did you first preprocessing the images?

**Comment by MrWeiminlee** [comment]
@wentaozhu  It stuck here about 10 minutes,is it normal?I have no idea what to do.Actually, I have preprocessed the images by running the prepare.py and nothing went wrong.Do you have any ideas?
Maybe the path in the config_training9 is incorrect?Would the data path in config_training9  should be same as the config_training which is used for the prepare?

**Comment by wentaozhu** [comment]
Yes. The path should use the path of preprocessing.

**Comment by MrWeiminlee** [comment]
@wentaozhu  Actually,the path is correct,but I don't understand why it stuck there.How many minutes did you take for training?

**Comment by wentaozhu** [comment]
I think we can run 100 epochs one day.

**Comment by MrWeiminlee** [comment]
@wentaozhu Sorry to bother you again,I have 2 GPU and I got the out of memory error,I saw other issues that give a solution,change the batch_size.I want to know what's your batch_size and what batch_size should I used, is it in the detector/main.py

parser.add_argument('-b', '--batch-size', default=16, type=int,
                    metavar='N', help='mini-batch size (default: 16)')
How could I change it?

**Comment by wentaozhu** [comment]
change batch size as 8 or 4 and have a try.

**Comment by MrWeiminlee** [comment]
@wentaozhu Thanks a lot! I want to know if the argument "--resume" is the same when I trained res18 and dpn3d26, are they use the same "064.ckpt"? Or I should use one of the detector/dpnmodels/*.ckpt when I want to trained dpn3d26? I look forward your help.

**Comment by wentaozhu** [comment]
I think 064 is for res18.
