### ISSUE TITLE
About test results.

### ISSUE THREAD

**Issue by anruoxi123** [wentaozhu/DeepLung#68]
Hello, I have reproduced the detection part of pulmonary nodules in your code, and after adding Dropout layer to the end of each residual block, the parameter of sensitivity has been improved strangely, but the FROC score has decreased and is only more than 60%, may I ask what is the reason for this? Thank you very much!

**Comment by wentaozhu** [comment]
Is the code has the dropout layer? How about adding dropout in the second last or third last layer?

**Comment by anruoxi123** [comment]
The source code was there before, but it was commented out, and I just opened the comments section.
![LRCB0 R}OEC8Z~(}G Q@XWC](https://user-images.githubusercontent.com/43407427/55127978-e43bcf00-514c-11e9-9378-d7754bb8d98c.png)

**Comment by wentaozhu** [comment]
You may try different ways of dropout.

**Comment by anruoxi123** [comment]
Ok, thank you very much!
