### ISSUE TITLE
list index out of range when getfroc

### ISSUE THREAD

**Issue by sea-ice** [wentaozhu/DeepLung#69]
Hello, first of all, the work was well done! and i have encountered a problem when i run the `frocwrtdetpepchlun16.py` script to get FROC.
![2019-04-03_220344](https://user-images.githubusercontent.com/25540882/55485650-710aef00-565d-11e9-8596-b915ffd6abd8.png)
Could you help point out my problems, please? Thank you!

**Comment by wentaozhu** [comment]
check whether you use the correct files.

**Comment by sea-ice** [comment]
At last i find the problem because i use python 3 and generate the csv files with blank lines between each row. Reference: [https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row](url). Thank you again!
