### ISSUE TITLE
run_training.sh

### ISSUE THREAD

**Issue by aszhanghuali** [wentaozhu/DeepLung#70]
@wentaozhu 您好，打扰一下。请问一下代码中的run_training.sh这个代码是什么？是运行完prepare.py之后直接运行run_training.sh吗？应该怎么运行?
期待您的讲解！谢谢！

**Comment by wentaozhu** [comment]
Yes.

**Comment by Alexander0211** [comment]
run_training.sh is a shell script, it can help you process all train _code. you can use “sh run_training.sh" or ”./run_training.sh“ to run it.
