### ISSUE TITLE
What are these files in detector/dpnmodel ?

### ISSUE THREAD

**Issue by Vast-Stars** [wentaozhu/DeepLung#71]
Are these files used as a dpn3d26 model checkpoint file? I download `fd9044.ckpt`  and use it to interface test data but get terrible `_pbb.npy` file ( it's too large to use `getcsv()` and `nms()`) . 

What are these files used to? And is there a well-trained  dpn3d26 model file that I could use directly?

**Comment by wentaozhu** [comment]
Yes. You can use it to test on Luna 19 dataset.

**Comment by MrWeiminlee** [comment]
@wentaozhu  I think I can use the pretrained model 064.ckpt to train resnet. But can I use it to train dpn3d26 model?

**Comment by wentaozhu** [comment]
You can use dpn models to train and the models are in https://github.com/wentaozhu/DeepLung/tree/master/detector/dpnmodel

**Comment by MrWeiminlee** [comment]
> You can use dpn models to train and the models are in https://github.com/wentaozhu/DeepLung/tree/master/detector/dpnmodel

Are these model pretrained model, or they have been well-trained?

**Comment by wentaozhu** [comment]
These models give the performance reported in DeepLung: Deep 3D Dual Path Nets for Automated Pulmonary Nodule Detection and Classification. IEEE WACV, 2018.
