### ISSUE TITLE
How can I conclude the file like 'LIDC-IDRI-mappingLUNA16'?

### ISSUE THREAD

**Issue by 501306162** [wentaozhu/DeepLung#72]
I don't know how to map the UID betwewn LIDC-IDRI and LUNA16.

**Comment by wentaozhu** [comment]
It is in https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/extclsshpinfo.py

You may read functions in https://github.com/wentaozhu/DeepLung/tree/master/nodcls/data

**Comment by 501306162** [comment]
emm,I know it is already here, but I don't know how to map the ID like this (StudyInstanceUID & SeriesInstanceUID). By checking the .raw filename ( according to .mhd file )and then to sort out? 
 






------------------ 原始邮件 ------------------
发件人: "Wentao Zhu"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 凌晨5:39
收件人: "wentaozhu/DeepLung"<DeepLung@noreply.github.com>;
抄送: "｛淘淘"<501306162@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wentaozhu/DeepLung] How can I conclude the file like'LIDC-IDRI-mappingLUNA16'? (#72)




It is in https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/extclsshpinfo.py
 
You may read functions in https://github.com/wentaozhu/DeepLung/tree/master/nodcls/data

**Comment by 501306162** [comment]
Oh,i think i find the reason. by sort the LIDC-IDRI's filelist
  thank you !  you are awesome to write this program
  

 ------------------ 原始邮件 ------------------
  发件人: "Wentao Zhu"<notifications@github.com>;
 发送时间: 2019年5月8日(星期三) 凌晨5:39
 收件人: "wentaozhu/DeepLung"<DeepLung@noreply.github.com>;
 抄送: "｛淘淘"<501306162@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [wentaozhu/DeepLung] How can I conclude the file like'LIDC-IDRI-mappingLUNA16'? (#72)

 

 
It is in https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/extclsshpinfo.py
 
You may read functions in https://github.com/wentaozhu/DeepLung/tree/master/nodcls/data

**Comment by wentaozhu** [comment]
Yes. After you download the lidc_idri, you can easily figure out how to sort out.
