### ISSUE TITLE
How to deal with Segmentation fault（core dumped）？

### ISSUE THREAD

**Issue by FancccyRay** [wentaozhu/DeepLung#75]
Hello！ each time when I tried to run main.py at 2 servers, I always met this problem,I nearly get crazy to this problem,can you tell me how to deal with it？
the debug info shows as follow：
#0  0x00007fff6938a496 in cudnnSetTensorNdDescriptor ()
   from /usr/local/cuda/lib64/libcudnn.so.5
#1  0x00007fff737136fc in set (stride=0x7fffafff4970, size=0x7fffafff4950, 
    dim=<optimized out>, dataType=CUDNN_DATA_FLOAT, 
    this=0x7ffec1d2069f <cuCtxGetDevice+207>)
    at torch/csrc/cudnn/Descriptors.h:26
#2  torch::cudnn::cudnn_convolution_add_bias (state=state@entry=0x14e93f0, 
    handle=handle@entry=0x7ffe7c089bb0, 
    dataType=dataType@entry=CUDNN_DATA_FLOAT, bias=bias@entry=0x13afe70, 
    output=output@entry=0x7ffe7c087670, 
    info=info@entry=0x7ffec1d2061f <cuCtxGetDevice+79>)
    at torch/csrc/cudnn/Conv.cpp:321
#3  0x00007fff73715f10 in torch::cudnn::cudnn_convolution_full_forward (
    state=0x14e93f0, handle=0x7ffe7c089bb0, 
    dataType=dataType@entry=CUDNN_DATA_FLOAT, 
    input=input@entry=0x7fffb22effb0, weight=weight@entry=0x14ec1c0, 
    bias=bias@entry=0x13afe70, output=output@entry=0x7ffe7c087670, pad=..., 
    stride=..., dilation=..., groups=groups@entry=1, 
    benchmark=benchmark@entry=true) at torch/csrc/cudnn/Conv.cpp:411
#4  0x00007fff7371b37f in THCUDNN_cudnn_convolution_full_forward (
    self=<optimized out>, args=<optimized out>, kwargs=<optimized out>)
    at torch/csrc/cudnn/cuDNN.cpp:115
#5  0x00007ffff718e302 in _PyCFunction_FastCallDict (func_obj=0x7fff73b88af8, 
---Type <return> to continue, or q <return> to quit---
    args=0x7ffe7c002300, nargs=<optimized out>, kwargs=0x0)
    at Objects/methodobject.c:231
#6  0x00007ffff7213b8c in call_function (pp_stack=0x7fffafff4f28, 
    oparg=<optimized out>, kwnames=0x0) at Python/ceval.c:4809
#7  0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#8  0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=4, globals=<optimized out>)
    at Python/ceval.c:4891
#9  0x00007ffff7213c88 in fast_function (kwnames=0x0, nargs=4, 
    stack=<optimized out>, func=0x7fff3fdf1158) at Python/ceval.c:4926
#10 call_function (pp_stack=0x7fffafff5158, oparg=<optimized out>, kwnames=0x0)
    at Python/ceval.c:4830
#11 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#12 0x00007ffff7212100 in _PyEval_EvalCodeWithName (_co=0x7fff3fe6b6f0, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=4, kwnames=0x0, kwargs=0x8, kwcount=0, kwstep=2, 
    defs=0x7fff3fde5fb0, defcount=1, kwdefs=0x0, closure=0x0, 
    name=0x7fff408dd688, qualname=0x7fff3fde71f0) at Python/ceval.c:4139
#13 0x00007ffff721239c in _PyFunction_FastCallDict (func=0x7fff3fdedea0, 
    args=0x7fffafff5390, nargs=4, kwargs=0x0) at Python/ceval.c:5042
#14 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff3fdedea0, 
---Type <return> to continue, or q <return> to quit---
    args=0x7fffafff5390, nargs=<optimized out>, kwargs=0x0)
    at Objects/abstract.c:2295
#15 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff3fdedea0, 
    obj=0x7fffec390a08, args=0x7fffe9027990, kwargs=0x0)
    at Objects/abstract.c:2358
#16 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c608, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#17 0x00007fff7331275e in THPFunction_do_forward (self=0x7fffec390a08, 
    inputs=0x7fffe90279d8) at torch/csrc/autograd/python_function.cpp:447
#18 0x00007ffff718e6a9 in PyCFunction_Call (func=0x7fffe902fea0, 
    args=0x7fffe90279d8, kwds=<optimized out>) at Objects/methodobject.c:114
#19 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902fea0, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#20 0x00007ffff71af44f in slot_tp_call (self=0x7fffec390a08, 
    args=0x7fffe90279d8, kwds=0x0) at Objects/typeobject.c:6194
#21 0x00007ffff7136c1e in _PyObject_FastCallDict (func=0x7fffec390a08, 
    args=<optimized out>, nargs=<optimized out>, kwargs=0x0)
    at Objects/abstract.c:2316
#22 0x00007ffff721395b in call_function (pp_stack=0x7fffafff58d8, 
    oparg=<optimized out>, kwnames=0x0) at Python/ceval.c:4833
#23 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#24 0x00007ffff7212100 in _PyEval_EvalCodeWithName (_co=0x7fff3fdf6a50, 
---Type <return> to continue, or q <return> to quit---
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=7, kwnames=0x0, kwargs=0x7fffec796b98, kwcount=0, kwstep=1, 
    defs=0x7fff3fde88f8, defcount=5, kwdefs=0x0, closure=0x0, 
    name=0x7fff3fdf4b20, qualname=0x7fff3fdf4b20) at Python/ceval.c:4139
#25 0x00007ffff7213b2a in fast_function (kwnames=<optimized out>, nargs=7, 
    stack=<optimized out>, func=0x7fff3fdf27b8) at Python/ceval.c:4950
#26 call_function (pp_stack=0x7fffafff5b78, oparg=<optimized out>, 
    kwnames=<optimized out>) at Python/ceval.c:4830
#27 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#28 0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=2, globals=<optimized out>)
    at Python/ceval.c:4891
#29 0x00007ffff7212515 in _PyFunction_FastCallDict (func=0x7fff3fd95510, 
    args=0x7fffafff5d40, nargs=2, kwargs=0x7fffe902ff78) at Python/ceval.c:4993
#30 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff3fd95510, 
    args=0x7fffafff5d40, nargs=<optimized out>, kwargs=0x7fffe902ff78)
    at Objects/abstract.c:2295
#31 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff3fd95510, 
    obj=0x7fffec393358, args=0x7fffe901cac8, kwargs=0x7fffe902ff78)
    at Objects/abstract.c:2358
#32 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c5c8, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
---Type <return> to continue, or q <return> to quit---
#33 0x00007ffff7217fc9 in do_call_core (kwdict=0x7fffe902ff78, 
    callargs=<optimized out>, func=0x7fffe902c5c8) at Python/ceval.c:5078
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:3377
#35 0x00007ffff7212100 in _PyEval_EvalCodeWithName (_co=0x7fff408de930, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=2, kwnames=0x0, kwargs=0x8, kwcount=0, kwstep=2, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0, name=0x7ffff7f85170, 
    qualname=0x7fff408df170) at Python/ceval.c:4139
#36 0x00007ffff721239c in _PyFunction_FastCallDict (func=0x7fff3fe10510, 
    args=0x7fffafff6130, nargs=2, kwargs=0x0) at Python/ceval.c:5042
#37 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff3fe10510, 
    args=0x7fffafff6130, nargs=<optimized out>, kwargs=0x0)
    at Objects/abstract.c:2295
#38 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff3fe10510, 
    obj=0x7fffec393358, args=0x7fffec393240, kwargs=0x0)
    at Objects/abstract.c:2358
#39 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c588, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#40 0x00007ffff71af44f in slot_tp_call (self=0x7fffec393358, 
    args=0x7fffec393240, kwds=0x0) at Objects/typeobject.c:6194
#41 0x00007ffff7136c1e in _PyObject_FastCallDict (func=0x7fffec393358, 
    args=<optimized out>, nargs=<optimized out>, kwargs=0x0)
---Type <return> to continue, or q <return> to quit---
    at Objects/abstract.c:2316
#42 0x00007ffff721395b in call_function (pp_stack=0x7fffafff6428, 
    oparg=<optimized out>, kwnames=0x0) at Python/ceval.c:4833
#43 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#44 0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=2, globals=<optimized out>)
    at Python/ceval.c:4891
#45 0x00007ffff7212515 in _PyFunction_FastCallDict (func=0x7fff3fda9950, 
    args=0x7fffafff65f0, nargs=2, kwargs=0x7fffe902ff30) at Python/ceval.c:4993
#46 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff3fda9950, 
    args=0x7fffafff65f0, nargs=<optimized out>, kwargs=0x7fffe902ff30)
    at Objects/abstract.c:2295
#47 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff3fda9950, 
    obj=0x7fffec393320, args=0x7fffec80fd30, kwargs=0x7fffe902ff30)
    at Objects/abstract.c:2358
#48 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c548, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#49 0x00007ffff7217fc9 in do_call_core (kwdict=0x7fffe902ff30, 
    callargs=<optimized out>, func=0x7fffe902c548) at Python/ceval.c:5078
#50 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:3377
#51 0x00007ffff7212100 in _PyEval_EvalCodeWithName (_co=0x7fff408de930, 
---Type <return> to continue, or q <return> to quit---
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=2, kwnames=0x0, kwargs=0x8, kwcount=0, kwstep=2, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0, name=0x7ffff7f85170, 
    qualname=0x7fff408df170) at Python/ceval.c:4139
#52 0x00007ffff721239c in _PyFunction_FastCallDict (func=0x7fff3fe10510, 
    args=0x7fffafff69e0, nargs=2, kwargs=0x0) at Python/ceval.c:5042
#53 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff3fe10510, 
    args=0x7fffafff69e0, nargs=<optimized out>, kwargs=0x0)
    at Objects/abstract.c:2295
#54 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff3fe10510, 
    obj=0x7fffec393320, args=0x7fffec80fcf8, kwargs=0x0)
    at Objects/abstract.c:2358
#55 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c508, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#56 0x00007ffff71af44f in slot_tp_call (self=0x7fffec393320, 
    args=0x7fffec80fcf8, kwds=0x0) at Objects/typeobject.c:6194
#57 0x00007ffff7136c1e in _PyObject_FastCallDict (func=0x7fffec393320, 
    args=<optimized out>, nargs=<optimized out>, kwargs=0x0)
    at Objects/abstract.c:2316
#58 0x00007ffff721395b in call_function (pp_stack=0x7fffafff6cd8, 
    oparg=<optimized out>, kwnames=0x0) at Python/ceval.c:4833
#59 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
---Type <return> to continue, or q <return> to quit---
#60 0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=3, globals=<optimized out>)
    at Python/ceval.c:4891
#61 0x00007ffff7212515 in _PyFunction_FastCallDict (func=0x7ffec2571c80, 
    args=0x7fffafff6ea0, nargs=3, kwargs=0x7fffe902fee8) at Python/ceval.c:4993
#62 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7ffec2571c80, 
    args=0x7fffafff6ea0, nargs=<optimized out>, kwargs=0x7fffe902fee8)
    at Objects/abstract.c:2295
#63 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7ffec2571c80, 
    obj=0x7fffec3932b0, args=0x7ffebfad0988, kwargs=0x7fffe902fee8)
    at Objects/abstract.c:2358
#64 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c4c8, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#65 0x00007ffff7217fc9 in do_call_core (kwdict=0x7fffe902fee8, 
    callargs=<optimized out>, func=0x7fffe902c4c8) at Python/ceval.c:5078
#66 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:3377
#67 0x00007ffff7212100 in _PyEval_EvalCodeWithName (_co=0x7fff408de930, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=3, kwnames=0x7ffff7f82060, kwargs=0x7ffff7f82068, kwcount=0, 
    kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, 
    name=0x7ffff7f85170, qualname=0x7fff408df170) at Python/ceval.c:4139
#68 0x00007ffff721239c in _PyFunction_FastCallDict (func=0x7fff3fe10510, 
---Type <return> to continue, or q <return> to quit---
    args=0x7fffafff7290, nargs=3, kwargs=0x7fffec798318) at Python/ceval.c:5042
#69 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff3fe10510, 
    args=0x7fffafff7290, nargs=<optimized out>, kwargs=0x7fffec798318)
    at Objects/abstract.c:2295
#70 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff3fe10510, 
    obj=0x7fffec3932b0, args=0x7ffebfad09c8, kwargs=0x7fffec798318)
    at Objects/abstract.c:2358
#71 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe902c048, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#72 0x00007ffff71af44f in slot_tp_call (self=0x7fffec3932b0, 
    args=0x7ffebfad09c8, kwds=0x7fffec798318) at Objects/typeobject.c:6194
#73 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffec3932b0, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#74 0x00007ffff7217fc9 in do_call_core (kwdict=0x7fffec798318, 
    callargs=<optimized out>, func=0x7fffec3932b0) at Python/ceval.c:5078
#75 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:3377
#76 0x00007ffff7212100 in _PyEval_EvalCodeWithName (_co=0x7fff3fdc74b0, 
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=5, kwnames=0x7ffff7f82060, kwargs=0x7ffff7f82068, kwcount=0, 
    kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, 
    qualname=0x0) at Python/ceval.c:4139
#77 0x00007ffff7212583 in PyEval_EvalCodeEx (_co=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>, 
    argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4160
#78 0x00007ffff716a1a1 in function_call (func=0x7fffe9029488, 
    arg=0x7fffec7fe2b0, kw=0x7fffe9027a68) at Objects/funcobject.c:604
#79 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffe9029488, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#80 0x00007ffff7217fc9 in do_call_core (kwdict=0x7fffe9027a68, 
    callargs=<optimized out>, func=0x7fffe9029488) at Python/ceval.c:5078
#81 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at Python/ceval.c:3377
#82 0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=1, globals=<optimized out>)
    at Python/ceval.c:4891
#83 0x00007ffff7213c88 in fast_function (kwnames=0x0, nargs=1, 
    stack=<optimized out>, func=0x7fff76471c80) at Python/ceval.c:4926
#84 call_function (pp_stack=0x7fffafff7a28, oparg=<optimized out>, kwnames=0x0)
    at Python/ceval.c:4830
#85 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#86 0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=1, globals=<optimized out>)
    at Python/ceval.c:4891
---Type <return> to continue, or q <return> to quit---
#87 0x00007ffff7213c88 in fast_function (kwnames=0x0, nargs=1, 
    stack=<optimized out>, func=0x7fff76471ea0) at Python/ceval.c:4926
#88 call_function (pp_stack=0x7fffafff7c58, oparg=<optimized out>, kwnames=0x0)
    at Python/ceval.c:4830
#89 0x00007ffff7216d40 in _PyEval_EvalFrameDefault (f=<optimized out>, 
    throwflag=<optimized out>) at Python/ceval.c:3295
#90 0x00007ffff7211514 in _PyFunction_FastCall (co=<optimized out>, 
    args=<optimized out>, nargs=1, globals=<optimized out>)
    at Python/ceval.c:4891
#91 0x00007ffff7212515 in _PyFunction_FastCallDict (func=0x7fff76471d08, 
    args=0x7fffafff7e20, nargs=1, kwargs=0x0) at Python/ceval.c:4993
#92 0x00007ffff7136ce6 in _PyObject_FastCallDict (func=0x7fff76471d08, 
    args=0x7fffafff7e20, nargs=<optimized out>, kwargs=0x0)
    at Objects/abstract.c:2295
#93 0x00007ffff7136f3c in _PyObject_Call_Prepend (func=0x7fff76471d08, 
    obj=0x7fffe901cb38, args=0x7ffff7f82048, kwargs=0x0)
    at Objects/abstract.c:2358
#94 0x00007ffff7136fd6 in PyObject_Call (func=0x7fffec7e3f08, 
    args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2246
#95 0x00007ffff7264302 in t_bootstrap (boot_raw=0x7fffec37beb8)
    at ./Modules/_threadmodule.c:998
#96 0x00007ffff6eb6e25 in start_thread () from /lib64/libpthread.so.0
#97 0x00007ffff62d334d in clone () from /lib64/libc.so.6

**Comment by wentaozhu** [comment]
Can you run other pytorch scripts like mnist example using GPU correctly?

**Comment by FancccyRay** [comment]
> Can you run other pytorch scripts like mnist example using GPU correctly?

Oh, sorry, I never tried other pytorch projects, this is first pytorch project I ran.

**Comment by FancccyRay** [comment]
> Can you run other pytorch scripts like mnist example using GPU correctly?
Thank you for your reply！I may need to run other pytorch script to test whether is the version or dependency problem
.

**Comment by FancccyRay** [comment]
> > Can you run other pytorch scripts like mnist example using GPU correctly?
> > Thank you for your reply！I may need to run other pytorch script to test whether is the version or dependency problem
> > .

Hi, Wentao, I can run other pytorch scripts successfully. I try to add print to find where the problem
comes, it stops at this line" output = net(data, coord)" at main.py.  I dont know why? Can you help me solve this?
By the way, I wonder how can you install the pytorch (0.1.10+ac9245a) , I can not find this version, I dont know if the version problem cause this?
