### ISSUE TITLE
What do the _pbb.npy and _lbb.npy mean?

### ISSUE THREAD

**Issue by sugurs** [wentaozhu/DeepLung#76]
After training and testing, the test program will generate corresponding _pbb.npy and _lbb.npy files for each sequence of MHD and RAW files, I met the problem when to understand  these output files. How to calculate the prediction accuracy for each sequence with the corresponding _pbb.npy and _lbb.npy files?

**Comment by wentaozhu** [comment]
I remember pbb is the probability of box and lbb is the ground truth of box if I am not wrong. This demo may help you understand the generated results https://github.com/wentaozhu/DeepLung/tree/master/DeepLungDetectionDemo
