### ISSUE TITLE
Question about anchor size settings

### ISSUE THREAD

**Issue by GGOBOND** [wentaozhu/DeepLung#78]
Hi,
I use this code to train other data sets that tpr has been 0% and tnr has been 100%. Is the size of the anchor related to the radius of the nodule? I see the code in the select_samples function for data.py in the code below, if it always  prints (['iou large', iou[mask]]), is it because the box size is set incorrectly?

 I hope you have time to answer my questions.

![TIM截图20190715211716](https://user-images.githubusercontent.com/40915797/61219062-f36b7a80-a745-11e9-88d3-e58e8108c9f3.png)

**Comment by wentaozhu** [comment]
No. Anchor size should be selected as close to radius size. It seems that iou large means you detected the box because iou >= th

**Comment by GGOBOND** [comment]
Thank you for your reply! I also want to ask if loss doesn't go down, and TPR is always 0%, what's the reason? I think the data and labels are correct.

**Comment by wentaozhu** [comment]
Can you reproduce the Luna dataset?

**Comment by GGOBOND** [comment]
Ok, I will download the data set again to see if there is any problem with the code. Thank you！
