### ISSUE TITLE
All the model parameter files you provide do not match the final version of the network structure  DPN3d26-FasterRCNN.

### ISSUE THREAD

**Issue by tricoffee** [wentaozhu/DeepLung#80]
All the model parameter files you provide do not match the final version of the network structure  DPN3d26-FasterRCNN.

**Comment by wentaozhu** [comment]
DPN models are in https://github.com/wentaozhu/DeepLung/tree/master/detector/dpnmodel
Res18 models are in https://github.com/wentaozhu/DeepLung/tree/master/detector/resmodel
