### ISSUE TITLE
How to compute probability for each nodule candidate

### ISSUE THREAD

**Issue by tricoffee** [wentaozhu/DeepLung#81]
The  field "probability" in this file <https://raw.githubusercontent.com/wentaozhu/DeepLung/master/evaluationScript/annotations/3DRes18FasterR-CNN.csv>  is used to calculate FROC. I wanna know how to compute probability for each nodule candidate.

**Comment by wentaozhu** [comment]
You may try this script https://github.com/wentaozhu/DeepLung/blob/master/evaluationScript/frocwrtdetpepchluna16.py

**Comment by tricoffee** [comment]
Thx

**Comment by tricoffee** [comment]
> You may try this script https://github.com/wentaozhu/DeepLung/blob/master/evaluationScript/frocwrtdetpepchluna16.py

Thx
