### ISSUE TITLE
问几个很基本的问题

### ISSUE THREAD

**Issue by Alphia** [wentaozhu/DeepLung#83]
我是深度学习的新人，有几个问题一直没搞清楚，请教一下
1. 训练模型的输入应该是图片，但是数据集里没看到图片。
2. 已经训练好的模型，怎么使用呢？readme里面提到模型在/detector/dpnmodel/ or ./detector/resmodel目录下，我看到10个ckpt文件，使用pytorch load之后，不知怎么用。
3. 我理解是用pytorch加载一个模型，然后以一个图片为输入，得倒一个标记了nodule的图片；但在DeepLungDetectionDemo里面我并没有看到加载现有模型并推演出有标记的图片。是我理解的有问题吗？

**Comment by Alphia** [comment]
另外，validate data是用来validate什么的？testdata是用来test什么的？

**Comment by Alphia** [comment]
另外，准确率怎么看？那个FROC是什么？Performance指的是处理一个图片的时间吗？

**Comment by Alphia** [comment]
@wentaozhu 请不吝赐教～

**Comment by wentaozhu** [comment]
> 我是深度学习的新人，有几个问题一直没搞清楚，请教一下
> 
> 1. 训练模型的输入应该是图片，但是数据集里没看到图片。
> 2. 已经训练好的模型，怎么使用呢？readme里面提到模型在/detector/dpnmodel/ or ./detector/resmodel目录下，我看到10个ckpt文件，使用pytorch load之后，不知怎么用。
> 3. 我理解是用pytorch加载一个模型，然后以一个图片为输入，得倒一个标记了nodule的图片；但在DeepLungDetectionDemo里面我并没有看到加载现有模型并推演出有标记的图片。是我理解的有问题吗？

https://github.com/wentaozhu/DeepLung/blob/master/DeepLungDetectionDemo/detector.ipynb Maybe this can help you.

**Comment by wentaozhu** [comment]
> 另外，准确率怎么看？那个FROC是什么？Performance指的是处理一个图片的时间吗？

https://github.com/wentaozhu/DeepLung/blob/master/evaluationScript/frocwrtdetpepchluna16.py

This is the FROC.

**Comment by Alphia** [comment]
非常感谢，解决了我的问题。不过又有了新的问题。
我使用pretrained model，10个ckpt对应10个subset，分别做了test。得到的结果只有lbb和nbb，在下一步运行frocwrtdetpepchluna16.py时，提示我找不到bbox1/predanno-1.5d3.csv。
1.是不是我遗漏了什么？或者是我哪儿理解错了？
2. 我理解frocwrtdetpepchluna16.py对每一个fold运行之后，会得到一个csv文件，10个csv文件合在一起，就是noduleCADEvaluationLUNA16.py运行是需要的3DRes18FasterR-CNN.csv，对吗？

**Comment by wentaozhu** [comment]
https://github.com/wentaozhu/DeepLung/blob/master/evaluationScript/frocwrtdetpepchluna16.py
Probably you should uncomment line 144.

**Comment by wentaozhu** [comment]
> 非常感谢，解决了我的问题。不过又有了新的问题。
> 我使用pretrained model，10个ckpt对应10个subset，分别做了test。得到的结果只有lbb和nbb，在下一步运行frocwrtdetpepchluna16.py时，提示我找不到bbox1/predanno-1.5d3.csv。
> 1.是不是我遗漏了什么？或者是我哪儿理解错了？
> 2. 我理解frocwrtdetpepchluna16.py对每一个fold运行之后，会得到一个csv文件，10个csv文件合在一起，就是noduleCADEvaluationLUNA16.py运行是需要的3DRes18FasterR-CNN.csv，对吗？

2 is right

**Comment by Alphia** [comment]
就是get_csv 报的错，124行试图读这个不存在的文件出的错：
f = open(bboxpath + 'predanno'+ str(detpthresh) + 'd3.csv', 'w')

**Comment by wentaozhu** [comment]
The bboxpath is not available. 'w' is writing, not reading. Please use English for communication.
