### ISSUE TITLE
What is the meaning of "maxeps" ?

### ISSUE THREAD

**Issue by tricoffee** [wentaozhu/DeepLung#85]
What is the meaning of "maxeps" in this file DeepLung/evaluationScript/noduleCADEvaluationLUNA16.py ?

**Comment by wentaozhu** [comment]
It is the number of epochs in the training https://github.com/wentaozhu/DeepLung/blob/master/run_training.sh

**Comment by tricoffee** [comment]
> It is the number of epochs in the training https://github.com/wentaozhu/DeepLung/blob/master/run_training.sh

What is the significance of calculating FROC for multiple epochs ?
What is the meaning of "frocarr" ?
What is Average FROC ?

**Comment by wentaozhu** [comment]
Please read the papers
Deeplung: 3d deep convolutional nets for automated pulmonary nodule detection and classification, WACV18
DeepEM: Deep 3D ConvNets With EM For Weakly Supervised Pulmonary Nodule Detection, MICCAI18
