### ISSUE TITLE
Questions about FROC evaluation

### ISSUE THREAD

**Issue by programwang007** [wentaozhu/DeepLung#86]
Hi Wentao, we have encountered some questions about FROC evaluation. Could you please give us some advice?
1.	In res18.py, why do we need to add 3?

```
for i in range(len(num_blocks_back)):                       
blocks = []
    for j in range(num_blocks_back[i]):
        if j == 0:
            if i==0:
                addition = 3    # why add 3?
            else:
                addition = 0
            blocks.append(PostRes(self.featureNum_back[i+1]+self.featureNum_forw[i+2]+addition, self.featureNum_back[i]))
        else:
            blocks.append(PostRes(self.featureNum_back[i], self.featureNum_back[i]))
    setattr(self, 'back' + str(i + 2), nn.Sequential(*blocks))
```

2.	We encountered ‘CUDA out of memory’ problem when testing. And I wonder if we must first run the test before evaluating FROC.
Without testing, error occurs when running ‘frocwrtdetpepchluna16.py ’:
```
ep 1 detp -1.5
Traceback (most recent call last):
  File "frocwrtdetpepchluna16.py", line 144, in <module>
    getcsv(detp, eps)
  File "frocwrtdetpepchluna16.py", line 124, in getcsv
    f = open(bboxpath + 'predanno'+ str(detpthresh) + 'd3.csv', 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/zot/project/codes/DeepLung_test/detector/results/res18/retrft969/1/predanno-1.5d3.csv'
 ```
It will be very grateful for your reply, thank you!

**Comment by wentaozhu** [comment]
I think #48  can help you.

For 1, you can easily plot the network structure and get a sense of the used network structure.

**Comment by programwang007** [comment]
Thanks for reply! But I can't get your idea about #48, we have done the data preprocessing step. In test phase, can batch size = 1 solve the GPU limited memory problem?

**Comment by wentaozhu** [comment]
You may have a try.
