### ISSUE TITLE
Some questions about the return value of the function getfrocvalue

### ISSUE THREAD

**Issue by HYB777** [wentaozhu/DeepLung#88]
**hello, when i run the frocwrtdetpepchluna16.py, i meet the error**
![err1](https://user-images.githubusercontent.com/25681785/63918618-9a467480-ca6f-11e9-850c-40ee7e2653bf.png)
![err0](https://user-images.githubusercontent.com/25681785/63918617-99adde00-ca6f-11e9-8f25-7d4ee392dcab.png)

**and then i find that the function getfrocvalue return nothing, but it should return the frocval.**
![err2](https://user-images.githubusercontent.com/25681785/63918416-3fad1880-ca6f-11e9-96ff-c760056f657a.png)
![err3](https://user-images.githubusercontent.com/25681785/63918417-3fad1880-ca6f-11e9-9764-100e6ce82623.png)

**Comment by wentaozhu** [comment]
Probably your prediction file or ground truth file is not correct.

**Comment by HYB777** [comment]
**But in the  getfrocvalue, it return noduleCADEvaluation(......), and noduleCADEvaluation return nothing, it just called collect function and evaluateCAD functio. Although evaluateCAD has return value, but it returns a tuple, and this tuple can't be returned by the noduleCADEvaluation.**

**Is this problem related to the prediction file or ground truth file?**

**Comment by HYB777** [comment]
**I saw your noduleCADEvaluationLUNA16compare.py, and it return frocv/7, I think I should use it?**

**Comment by wentaozhu** [comment]
You may get it from #90 #91 
Maybe it is caused by that the returned detection box is empty. Try to tune the detection threshold. And check your trained model. I suggest you firstly use my pretrained model to be familiar with the pipeline.

**Comment by HYB777** [comment]
Thank you! I think I have solved it!

**Comment by BelieferQAQ** [comment]
> Thank you! I think I have solved it


> You may get it from #90 #91 Maybe it is caused by that the returned detection box is empty. Try to tune the detection threshold. And check your trained model. I suggest you firstly use my pretrained model to be familiar with the pipeline.



> Thank you! I think I have solved it!
could you tell me how do you solved it? Thank you
