### ISSUE TITLE
No match from LIDC-IDRI annotation

### ISSUE THREAD

**Issue by pigen01** [wentaozhu/DeepLung#89]
While reproducing your work, I found no match from LIDC-IDRI annotation (nocls/extclsshpinfo.py), since the antdictscan.keys are like

0989_30080-50856
0990_30042-68974
0991_07064
0993_3258-65588
...

but the pid+'_'+srcid in lunantdictlidc are like

0122_1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896446896160048741492
0447_1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524522225658609808059
0447_1.3.6.1.4.1.14519.5.2.1.6279.6001.109002525524522225658609808059
...

What's wrong?

**Comment by wentaozhu** [comment]
0122_1.3.6.1.4.1.14519.5.2.1.6279.6001.108197895896446896160048741492 is right

**Comment by pigen01** [comment]
but the data directory are like this, 
LIDI-IDRI-0042
   01-01-2000-33377
       3000579-20341
             000001.dcm
             ...
my LIDI-IDRI dataset is downloaded from https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#40c34911903e43bd8eb1c0677aa6f3e7

Is that the matter of dataset updating? I have tried to debug the code like this. 

```
      for dcm in os.listdir(os.path.join(*[LIDCpath, 'LIDC-IDRI-'+pid, sdu, srs])):
        if dcm.endswith('.dcm'):
          RefDs = dicom.read_file(os.path.join(*[LIDCpath, 'LIDC-IDRI-'+pid, sdu, srs, dcm]))
          # print scan, str(RefDs[0x20, 0x11].value)
          if str(RefDs[0x20, 0x11].value) == scan or scan == '0': 
            if hasscan: print ('rep', pid, sdu, srs)
            hasscan = True
            antdictscan[pid] = (sdu, srs, v)
            break
      if hasscan: break
  if not hasscan: print ('not found', pid, scan, sdu, srs)
```
```
for srcid, lunaantlidc in lunantdictlidc.items():
  lunaantdictnodid[srcid] = []
  pid, stdid = sidmap[srcid]
  # print pid
  pid = pid[len('LIDC-IDRI-'):]
  for lunantdictlidcsub in lunaantlidc:
    lunaant = lunantdictlidcsub[0]
    voxcrd = lunantdictlidcsub[1] # z y x
    mindist, minidx = 1e8, -1
    if srcid in ['1.3.6.1.4.1.14519.5.2.1.6279.6001.174692377730646477496286081479', '1.3.6.1.4.1.14519.5.2.1.6279.6001.300246184547502297539521283806']:
      continue
    
    for idx, lidcant in enumerate(antdictscan[pid][2]):
      dist = math.pow(voxcrd[0] - lidcant[3], 2) # z
      dist += math.pow(voxcrd[1] - lidcant[4], 2) # y
      dist += math.pow(voxcrd[2] - lidcant[5], 2) # x
      print(dist)
      if dist < mindist:
        mindist = dist
        minidx = idx
    if mindist > 71:#15.1:
      print (srcid, pid, voxcrd, antdictscan[pid], mindist)
    maxdist = max(maxdist, mindist)
    lunaantdictnodid[srcid].append([lunaant, antdictscan[pid][2][minidx][6:]])
```

It seems working, but I am not quite sure.

**Comment by wentaozhu** [comment]
> but the data directory are like this,
> LIDI-IDRI-0042
> 01-01-2000-33377
> 3000579-20341
> 000001.dcm
> ...
> my LIDI-IDRI dataset is downloaded from https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#40c34911903e43bd8eb1c0677aa6f3e7
> 
> Is that the matter of dataset updating? I have tried to debug the code like this.
> 
> ```
>       for dcm in os.listdir(os.path.join(*[LIDCpath, 'LIDC-IDRI-'+pid, sdu, srs])):
>         if dcm.endswith('.dcm'):
>           RefDs = dicom.read_file(os.path.join(*[LIDCpath, 'LIDC-IDRI-'+pid, sdu, srs, dcm]))
>           # print scan, str(RefDs[0x20, 0x11].value)
>           if str(RefDs[0x20, 0x11].value) == scan or scan == '0': 
>             if hasscan: print ('rep', pid, sdu, srs)
>             hasscan = True
>             antdictscan[pid] = (sdu, srs, v)
>             break
>       if hasscan: break
>   if not hasscan: print ('not found', pid, scan, sdu, srs)
> ```
> 
> ```
> for srcid, lunaantlidc in lunantdictlidc.items():
>   lunaantdictnodid[srcid] = []
>   pid, stdid = sidmap[srcid]
>   # print pid
>   pid = pid[len('LIDC-IDRI-'):]
>   for lunantdictlidcsub in lunaantlidc:
>     lunaant = lunantdictlidcsub[0]
>     voxcrd = lunantdictlidcsub[1] # z y x
>     mindist, minidx = 1e8, -1
>     if srcid in ['1.3.6.1.4.1.14519.5.2.1.6279.6001.174692377730646477496286081479', '1.3.6.1.4.1.14519.5.2.1.6279.6001.300246184547502297539521283806']:
>       continue
>     
>     for idx, lidcant in enumerate(antdictscan[pid][2]):
>       dist = math.pow(voxcrd[0] - lidcant[3], 2) # z
>       dist += math.pow(voxcrd[1] - lidcant[4], 2) # y
>       dist += math.pow(voxcrd[2] - lidcant[5], 2) # x
>       print(dist)
>       if dist < mindist:
>         mindist = dist
>         minidx = idx
>     if mindist > 71:#15.1:
>       print (srcid, pid, voxcrd, antdictscan[pid], mindist)
>     maxdist = max(maxdist, mindist)
>     lunaantdictnodid[srcid].append([lunaant, antdictscan[pid][2][minidx][6:]])
> ```
> 
> It seems working, but I am not quite sure.

**Comment by wentaozhu** [comment]
Congratulations!
