### ISSUE TITLE
The reported total recall rate of 94.6

### ISSUE THREAD

**Issue by QuantScientist** [wentaozhu/DeepLung#9]
Dear Team, 
In your report, you provide the folowing details for each fold: 
"Method	Deep 3D Res18	Deep 3D DPN26 Fold 0	0.8610	0.8750 Fold 1	0.8538	0.8783 Fold 2	0.7902 0.8170 Fold 3	0.7863 0.7731 Fold 4	0.8795	0.8850 Fold 5	0.8360 0.8095 Fold 6	0.8959 0.8649 Fold 7	0.8700 0.8816 Fold 8	0.8886	0.8668 Fold 9	0.8041 0.8122" 

Each of these numbers is evidently less than **0.9**.  

Later in the paper, you state that:
"R-CNN has a total recall rate **94.6%** for all the detected nodules, while 3D DPN26 Faster R-CNN has a recall rate **95.8%.**"
![2018-03-27 13_18_17-wacv18_final 2 pdf](https://user-images.githubusercontent.com/18743986/37961585-653a798c-31c1-11e8-807c-a8b399018030.png)

How were these results calculated, e.g the quoted total recall rates of   **94.6%** and  **95.8%.** ? 
If each results on each fold is less than 90% how can the average be more than 90%?

Many thanks,

**Comment by wentaozhu** [comment]
The total recall means for total detected nodules, not based on false positives as 8. I am sorry for the misunderstanding.
