### ISSUE TITLE
data file miss

### ISSUE THREAD

**Issue by pigen01** [wentaozhu/DeepLung#90]
nodcls/data/humanperformance.py
```
# load predition array
pixdimpred = np.load('../../../CTnoddetector/training/nodcls/besttestpred.npy')
```
Where can I find the "besttestpred.npy"?

**Comment by wentaozhu** [comment]
It is from your trained classifier.

**Comment by wentaozhu** [comment]
In the training of classifier, the code will save the best model automatically.

**Comment by 3learning12340** [comment]
@pigen01 hello, did you find the besttestpred.npy? I met the same problem, I can't find the besttestpred.npy and don't know how to generate it

**Comment by wentaozhu** [comment]
You can train the classifier based on the code https://github.com/wentaozhu/DeepLung/blob/master/nodcls/main_nodcls.py
And write a script to get the prediction.
