### ISSUE TITLE
problem about evaluationScript

### ISSUE THREAD

**Issue by penghuazhai** [wentaozhu/DeepLung#91]
Hello, I am now to complete the test of the model using your model, but I do not train a new model.  When I want to run. / evaluationScript frocwrtdetpepchluna16. py files, but I meet the error of csv file can not be found. Please give me some advises.
![2019-09-25 09-01-52 的屏幕截图](https://user-images.githubusercontent.com/50010117/65561215-3df24a00-df74-11e9-9f85-4a4821f6babf.png)

**Comment by penghuazhai** [comment]
I have uncomment Line 144  DeepLung/evaluationScript/frocwrtdetpepchluna16.py  getcsv(detp, eps)

**Comment by pigen01** [comment]
Do you have some problem about function getfrocvalue like this

```
D:\ProgramData\Anaconda_Build1\Anaconda3\envs\pytorch\lib\site-packages\matplotlib\font_manager.py:1241: UserWarning: findfont: Font family ['normal'] not found. Falling back to DejaVu Sans.
  (prop.get_family(), self.defaultFamily[fontext]))
F:\Yepj\04_DeepLearning\project05_lung_nodule\luna16\CSVFILES\subset9\annotations.csv
Total number of included nodule annotations: 105
Total number of nodule annotations: 4328
(1000, 10000)
0.6693877551020408 16.0
[]
[None, None]
Traceback (most recent call last):
  File "frocwrtdetpepchluna16.py", line 175, in <module>
    getfroc(detp, eps)
  File "frocwrtdetpepchluna16.py", line 162, in getfroc
    if maxfroc < max(froclist):
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by wentaozhu** [comment]
@penghuazhai Please read readme first https://github.com/wentaozhu/DeepLung/blob/master/README.md

"You can directly run noduleCADEvaluationLUNA16.py, and get the performance in the paper."

If you run frocwrtdetpepchluna16, you need first to get the csv files for the prediction of detection. 

To use the pre-trained model to test directly, you need to modify run_training.sh https://github.com/wentaozhu/DeepLung/blob/master/run_training.sh

`

#!/bin/bash
set -e

cd detector
maxeps=150
f=9
EPOCH_PRETRAIN=PRETRAINED_EPOCH
for (( i=$EPOCH_PRETRAIN; i<=$EPOCH_PRETRAIN; i+=1)) 
do
    echo "process $i epoch"
	
	if [ $i -lt 10 ]; then
	    CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 32 --resume results/res18/retrft96$f/00$i.ckpt --test 1 --save-dir res18/retrft96$f/ --config config_training$f
	elif [ $i -lt 100 ]; then 
	    CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 32 --resume results/res18/retrft96$f/0$i.ckpt --test 1 --save-dir res18/retrft96$f/ --config config_training$f
	elif [ $i -lt 1000 ]; then
	    CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python main.py --model res18 -b 32 --resume results/res18/retrft96$f/$i.ckpt --test 1 --save-dir res18/retrft96$f/ --config config_training$f
	else
	    echo "Unhandled case"
    fi

    if [ ! -d "results/res18/retrft96$f/val$i/" ]; then
        mkdir results/res18/retrft96$f/val$i/
    fi
    mv results/res18/retrft96$f/bbox/*.npy results/res18/retrft96$f/val$i/
done 

`

**Comment by wentaozhu** [comment]
@pigen01 Maybe it is caused by that the returned detection box is empty. Try to tune the detection threshold. And check your trained model. I suggest you firstly use my pretrained model to be familiar with the pipeline.

**Comment by ljk1072911239** [comment]
> Do you have some problem about function getfrocvalue like this
> 
> ```
> D:\ProgramData\Anaconda_Build1\Anaconda3\envs\pytorch\lib\site-packages\matplotlib\font_manager.py:1241: UserWarning: findfont: Font family ['normal'] not found. Falling back to DejaVu Sans.
>   (prop.get_family(), self.defaultFamily[fontext]))
> F:\Yepj\04_DeepLearning\project05_lung_nodule\luna16\CSVFILES\subset9\annotations.csv
> Total number of included nodule annotations: 105
> Total number of nodule annotations: 4328
> (1000, 10000)
> 0.6693877551020408 16.0
> []
> [None, None]
> Traceback (most recent call last):
>   File "frocwrtdetpepchluna16.py", line 175, in <module>
>     getfroc(detp, eps)
>   File "frocwrtdetpepchluna16.py", line 162, in getfroc
>     if maxfroc < max(froclist):
> TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
> ```

How can you solve this issue? I encounter it. Thanks.

**Comment by wentaozhu** [comment]
> > Do you have some problem about function getfrocvalue like this
> > ```
> > D:\ProgramData\Anaconda_Build1\Anaconda3\envs\pytorch\lib\site-packages\matplotlib\font_manager.py:1241: UserWarning: findfont: Font family ['normal'] not found. Falling back to DejaVu Sans.
> >   (prop.get_family(), self.defaultFamily[fontext]))
> > F:\Yepj\04_DeepLearning\project05_lung_nodule\luna16\CSVFILES\subset9\annotations.csv
> > Total number of included nodule annotations: 105
> > Total number of nodule annotations: 4328
> > (1000, 10000)
> > 0.6693877551020408 16.0
> > []
> > [None, None]
> > Traceback (most recent call last):
> >   File "frocwrtdetpepchluna16.py", line 175, in <module>
> >     getfroc(detp, eps)
> >   File "frocwrtdetpepchluna16.py", line 162, in getfroc
> >     if maxfroc < max(froclist):
> > TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
> > ```
> 
> How can you solve this issue? I encounter it. Thanks.

From the error, it seems the detection results are not good because you get "[]". Please carefully check your results and debug step by step.
