### ISSUE TITLE
How to get the pretrained model?

### ISSUE THREAD

**Issue by HYB777** [wentaozhu/DeepLung#93]
Hi~, I have run the model without loading the 064.ckpt, but the result is not good. I think I should load the 064.ckpt, and I also wonder how do you get the 064.ckpt？ Thank you!

**Comment by wentaozhu** [comment]
This is the detection pretrained model https://github.com/wentaozhu/DeepLung/tree/master/detector

**Comment by HYB777** [comment]
But how do you get the pretrained model? I mean how to train it?

**Comment by wentaozhu** [comment]
Read readme in https://github.com/wentaozhu/DeepLung

https://github.com/wentaozhu/DeepLung/blob/master/run_training.sh

f is the fold.

**Comment by HYB777** [comment]
Which dataset did you use to train the model 064.ckpt?

**Comment by wentaozhu** [comment]
LUNA16 https://luna16.grand-challenge.org/

**Comment by wentaozhu** [comment]
#109
