### ISSUE TITLE
关于路径

### ISSUE THREAD

**Issue by hengliang8** [wentaozhu/DeepLung#96]
在dcet2cls.py中的
preprocesspath = '/media/data1/wentao/tianchi/luna16/cls/crop_v3/'
preprocessallpath = '/media/data1/wentao/tianchi/luna16/preprocess/lunaall/'
请问第一个路径是prepare.py产生的文件路径吗
感谢

**Comment by wentaozhu** [comment]
The second path is from prepare.py. The first path may be from https://github.com/wentaozhu/DeepLung/tree/master/nodcls/data

**Comment by hengliang8** [comment]
Thank you
