### ISSUE TITLE
What is the role of the parameter 'coord'?

### ISSUE THREAD

**Issue by USTC-yzy1996** [wentaozhu/DeepLung#98]
在你们的代码中，经过数据预处理后得到了一个参数coord。在搭建神经网络时，以res18为例，self.back2中有定义额外的channel。在forward中，这个额外的channel就是为coord准备的。这个coord参数是如何得到的？它有什么作用和含义？为什么在原论文中没有提到这个参数？如果将这个参数删去会对结果造成什么影响？希望您解答一下我的困惑，感谢您。

In your code, after the data is preprocessed, a parameter coord is obtained. When building a neural network, take res18 as an example. There are additional channels defined in self.back2. In forward, this additional channel is prepared for coord. 

The code in res18.py:
`comb2 = self.back2(torch.cat((rev2, out2,coord), 1))`

How is this coord parameter obtained? What is its meaning and role? Why is this parameter not mentioned in the Deeplung paper? If you delete this parameter, what effect will it have on the result? I hope you can answer my questions, thank you very much.

**Comment by wentaozhu** [comment]
That is the crop coordinate of the current batch. There is no effect if you delete this parameter.

**Comment by perhapzz** [comment]
awesome
